import type { DiagnosticQuestion } from './diagnosticData';
/* Généré depuis la grille 360 v5.1 TOURISME — document.xml */
export const VOLETS = [
  { id:1, title:"COMMERCIALE ET FORCE DE VENTE", subtitle:"Comment vous trouvez, convertissez et gardez vos clients ." },
  { id:2, title:"VISIBILITÉ, MARKETING ET COMMUNICATION", subtitle:"Comment vous êtes vus, choisis et recommandés." },
  { id:3, title:"RH, FICHES DE POSTE, OUTILS DE TRAVAIL ET ORGANISATION", subtitle:"Comment l'équipe est organisée, outillée et fidélisée." },
  { id:4, title:"RÉDUCTION DES CHARGES ET COMPTABILITÉ ANALYTIQUE", subtitle:"Ce que coûte l'activité et ce qu'elle rapporte." },
] as const;

export const QUESTIONS:DiagnosticQuestion[] = [
  { id:"1A1", starred:true, internal:true, title:"Objectif chiffré", question:"Quel objectif de réservations avez-vous fixé par saison et par canal, et quel taux d'occupation visez-vous ?", relance:"Qui le connaît dans l'équipe ? Quand l'avez-vous ajusté pour la dernière fois ?", besoinAcces:false, levels:["Aucun objectif, aucun chiffre en tête","Objectif oral, jamais comparé au réel","Objectif écrit, comparé au réel de temps en temps","Objectif écrit, comparé au réel chaque mois, équipe informée","Objectif par saison et canal, suivi chaque semaine, écart analysé, action corrective datée"], weight:3,type:'Interne' },
  { id:"1A2", starred:true, internal:true, title:"Origine des demandes", question:"Sur vos 20 dernières réservations, combien viennent de chaque canal (direct, plateformes, conciergeries et agences, entreprises, bouche-à-oreille) ?", relance:"Demandez-vous « comment nous avez-vous connus ? » aux réservations directes ? Qui suit la répartition par canal ?", besoinAcces:false, levels:["Aucune idée de la provenance","Impression générale, aucun chiffre","Sources principales connues, sans pourcentage","Sources chiffrées en pourcentage sur les 3 derniers mois","Sources chiffrées chaque mois, coût et résultat par source, efforts réorientés"], weight:3,type:'Interne' },
  { id:"1A3", starred:true, internal:true, title:"Part des réservations directes", question:"Sur 12 mois, quelle part de vos réservations est directe (téléphone, site, courriel, sur place), et combien payez-vous de commissions aux plateformes ?", relance:"Quel montant de commissions sur 12 mois ? Quelle part sur une seule plateforme ?", besoinAcces:true, levels:["Moins de 10 %","10 à 20 %","20 à 35 %","35 à 50 %","Plus de 50 %, commissions suivies"], weight:3,type:'Interne' },
  { id:"1A4", starred:true, internal:true, title:"Transformation", question:"Sur 10 demandes de devis ou de disponibilités, combien deviennent des réservations, et en combien de temps répondez-vous ?", relance:"Que faites-vous quand vous êtes complet : alternative, liste d'attente, rien ?", besoinAcces:false, levels:["Jamais compté, réponses en plus de 48 h","Estimation vague, réponse sous 24 à 48 h","Taux connu à peu près, réponse dans la journée","Taux mesuré chaque mois, réponse sous 2 h en journée","Taux mesuré par canal, réponse sous 30 min, relance automatique des devis sans suite"], weight:3,type:'Interne' },
  { id:"1A5", starred:false, internal:true, title:"Tarifs et offres", question:"Vos tarifs sont-ils écrits par saison et par canal, comparés à ceux de 3 concurrents directs, et révisés au moins une fois par an ?", relance:"Quelle offre vous rapporte le plus de marge ? Laquelle vous coûte plus qu'elle ne rapporte ?", besoinAcces:false, levels:["Aucune grille écrite, tarifs donnés au cas par cas","Grille ancienne ou incomplète","Grille écrite et claire, non révisée depuis plus d'un an","Grille révisée chaque année après comparaison avec 3 concurrents","Offres packagées, marge connue par offre, tarifs ajustés selon la demande"], weight:2,type:'Interne' },
  { id:"1A6", starred:false, internal:true, title:"Relance et fidélisation", question:"Avant l'arrivée, pendant le séjour et après le départ, que prévoyez-vous pour que le client revienne, dépense plus ou recommande (message, concierge ou réception, offre de retour) ?", relance:"Qui, à la réception ou à la conciergerie, propose sorties, services et ventes additionnelles ? Quelle part de clients revient dans l'année ?", besoinAcces:false, levels:["Aucune action, retour non mesuré","Gestes spontanés, sans suivi (un mot à l'arrivée)","Message avant ou après séjour pour certains clients, retour estimé","Parcours en 3 temps pour la majorité, taux de retour et ventes additionnelles mesurés","Parcours écrit, concierge ou réception formés à proposer, retour, ventes additionnelles et recommandations mesurés avec objectif"], weight:2,type:'Interne' },
  { id:"1A7", starred:false, internal:true, title:"Responsable commercial", question:"Qui est responsable du développement commercial, combien d'heures par semaine y consacre-t-il, et sur quels résultats est-il suivi ?", relance:"Que se passe-t-il sur ce sujet quand cette personne est absente ?", besoinAcces:false, levels:["Personne, rien de défini","Le dirigeant quand il a le temps (moins d'1 h par semaine)","Le dirigeant, avec un créneau fixe chaque semaine","Une personne désignée, avec des objectifs écrits","Une personne formée, objectifs écrits, point hebdomadaire, résultats partagés"], weight:2,type:'Interne' },
  { id:"1B1", starred:true, internal:false, title:"Demande non servie", question:"Quelle clientèle, quel séjour, quel package ou quel événement le marché demande-t-il sans que vous le proposiez ? Combien de demandes avez-vous refusées le mois dernier ?", relance:"Quelle demande revient le plus souvent ? Que faudrait-il pour la servir ?", besoinAcces:false, levels:["Aucune idée","Soupçon, sans chiffre","Demande identifiée et chiffrée, rien de lancé","Demande identifiée, test lancé avec objectif","Demande exploitée, résultats mesurés"], enjeu:3,type:'Opportunité' },
  { id:"1B2", starred:true, internal:false, title:"Concurrent proche", question:"Si un concurrent proche baisse ses prix de 10 % ou ouvre à côté de chez vous, combien de clients risquez-vous de perdre, et quelle parade est prévue ?", relance:"Qui sont vos 2 concurrents les plus proches, et en quoi êtes-vous différent ?", besoinAcces:false, levels:["Très exposé, aucune parade","Exposé, parade improvisée","Risque connu, parade partielle","Offre différenciée, clients fidèles","Position de référence, peu sensible au prix"], enjeu:3,type:'Menace' },
  { id:"1B3", starred:false, internal:false, title:"Conciergeries et partenaires apporteurs", question:"Travaillez-vous avec des conciergeries (locations, hôtels, résidences), des agences ou des entreprises qui vous envoient des clients ? Combien de réservations par mois, avec quelle commission ?", relance:"Qui est votre contact chez chacun ? Quel taux de commission, quel délai de paiement ? Quand avez-vous renégocié pour la dernière fois ?", besoinAcces:false, levels:["Aucun partenaire apporteur","Un ou deux, relation informelle, volume et commission mal connus","Plusieurs, volume estimé, commission non comparée","Plusieurs, volume et commission suivis, contact nommé chez chacun","Accords écrits (tarif, commission, délai de paiement), volume mesuré, partenaires comparés et renégociés chaque année"], enjeu:2,type:'Opportunité' },
  { id:"2A1", starred:true, internal:true, title:"Fiche Google", question:"Ouvrons votre fiche Google : est-elle revendiquée, complète (horaires, téléphone, catégorie, photos, lien de réservation) et à jour ?", relance:"Les horaires des jours fériés sont-ils justes ? Qui gère la fiche ?", besoinAcces:false, levels:["Absente, non revendiquée, ou informations fausses","Revendiquée, informations incomplètes","Complète : horaires, téléphone, catégorie, photos","Complète, photos de moins de 6 mois, lien d'action actif","Complète, publication au moins mensuelle, questions et avis traités sous 48 h"], weight:3,type:'Interne' },
  { id:"2A2", starred:true, internal:true, title:"Site internet", question:"Depuis un téléphone, combien de clics et de minutes faut-il à un visiteur pour réserver en direct (avec acompte ou paiement) sur votre site ?", relance:"Faisons le test en séance. Combien de visites par mois, et combien de demandes en ligne ?", besoinAcces:false, levels:["Pas de site","Site ancien ou illisible sur mobile","Site à jour et lisible sur mobile, aucune action en ligne","Action en ligne possible en moins de 5 clics","Action en ligne complète, visites et conversions suivies chaque mois"], weight:3,type:'Interne' },
  { id:"2A3", starred:true, internal:true, title:"Avis en ligne", question:"Combien d'avis avez-vous sur chaque plateforme (Google, Booking, TripAdvisor…), avec quelle note, et à quel pourcentage répondez-vous ? Comment en obtenez-vous de nouveaux ?", relance:"Quel est le dernier avis négatif, et comment avez-vous répondu ?", besoinAcces:false, levels:["Moins de 10 avis, ou note sous 3,5","10 à 30 avis, aucune réponse","30 à 60 avis, note de 4 ou plus, réponses rares","Plus de 60 avis, note de 4,3 ou plus, réponse à la plupart","Plus de 100 avis, note de 4,5 ou plus, réponse à tous, demande d'avis systématique"], weight:3,type:'Interne' },
  { id:"2A4", starred:false, internal:true, title:"Réseaux sociaux", question:"À quelle fréquence publiez-vous sur les réseaux utilisés par votre cible, et qui s'en charge ?", relance:"Quel réseau vous a déjà rapporté une demande ? Combien ?", besoinAcces:false, levels:["Jamais, ou aucun compte","Moins d'une fois par mois","Environ 2 fois par mois","Chaque semaine","2 à 3 fois par semaine, avec un calendrier"], weight:1,type:'Interne' },
  { id:"2A5", starred:false, internal:true, title:"Identité visuelle", question:"Mettons côte à côte votre site, vos réseaux, votre signalétique et vos documents : un inconnu reconnaît-il la même structure ?", relance:"Existe-t-il une charte écrite (logo, couleurs, ton) ?", besoinAcces:false, levels:["Aucune identité","Logo ancien, supports hétérogènes","Identité correcte, quelques incohérences","Identité cohérente sur site, réseaux et papier","Identité forte, charte écrite, reconnaissable d'un coup d'œil"], weight:1,type:'Interne' },
  { id:"2A6", starred:false, internal:true, title:"Message clé", question:"En une phrase, pourquoi vous choisit-on plutôt qu'un concurrent proche ? Qu'en diraient 3 de vos clients ?", relance:"Cette phrase figure-t-elle sur votre site et sur votre fiche Google ?", besoinAcces:false, levels:["Aucun message clair","Message générique (qualité, sérieux, proximité)","Message clair, non repris partout","Message clair, repris sur le site, la fiche Google et les supports","Message différenciant, vérifié auprès d'au moins 5 clients, repris partout"], weight:2,type:'Interne' },
  { id:"2A7", starred:false, internal:true, title:"Budget et résultats", question:"Combien dépensez-vous par an en communication (temps compris), et quel nombre de réservations en découle ?", relance:"Quelle action a le mieux marché l'an dernier ? Laquelle arrêteriez-vous ?", besoinAcces:false, levels:["Aucun budget, aucun suivi","Budget flou, aucun suivi","Budget connu, retours estimés","Budget fixé, retours mesurés par action","Budget par canal, coût par réservation connu et comparé"], weight:2,type:'Interne' },
  { id:"2B1", starred:false, internal:false, title:"Recherches en ligne", question:"Tapez sur Google ce que tape quelqu'un qui vous cherche dans votre zone (métier + ville) : savez-vous ce qui est cherché, et apparaissez-vous en première page ?", relance:"Quelles 3 recherches voudriez-vous gagner ?", besoinAcces:false, levels:["Aucune idée de ce qui est cherché, absent des résultats","Intuition seulement, absent de la première page","Quelques recherches testées, présent seulement sur votre nom","Recherches principales connues, première page sur au moins 2 requêtes","Recherches suivies, première page sur la plupart des requêtes clés"], enjeu:2,type:'Opportunité' },
  { id:"2B2", starred:true, internal:false, title:"Visibilité du concurrent", question:"Pour la même recherche, votre concurrent le plus proche apparaît-il avant vous, et avec combien d'avis de plus ou de moins ?", relance:"Quel concurrent a récemment refait son site ou ses photos ?", besoinAcces:false, levels:["Très largement plus visible","Nettement plus visible","À peu près égal","Vous êtes devant","Vous êtes la référence locale"], enjeu:3,type:'Menace' },
  { id:"2B3", starred:false, internal:false, title:"Relais : concierges et conciergeries", question:"Les concierges d'hôtels, les conciergeries et les offices de tourisme de votre zone vous recommandent-ils ? Les avez-vous rencontrés cette année, avec une offre ou un tarif partenaire écrit ?", relance:"Combien de concierges pourriez-vous nommer ? Quelle est votre dernière action envers eux (visite, invitation, dossier, tarif) ?", besoinAcces:false, levels:["Aucun contact avec les concierges de la zone","Contacts occasionnels, aucune offre dédiée","Quelques concierges connus, offre informelle, retombées estimées","Concierges démarchés, tarif partenaire écrit, recommandations comptées","Réseau animé (visites, invitations, offre dédiée), recommandations mesurées et réinvesties"], enjeu:2,type:'Opportunité' },
  { id:"3A1", starred:false, internal:true, title:"Rôles", question:"Si vous êtes absent une semaine, qui décide quoi ? Chacun sait-il de quoi il est responsable ?", relance:"Dernière absence du dirigeant : qu'est-ce qui a bloqué ?", besoinAcces:false, levels:["Tout remonte au dirigeant","Rôles flous, doublons fréquents","Rôles connus oralement","Rôles écrits, remplaçant identifié pour les postes clés","Rôles écrits, remplaçants formés, une semaine d'absence du dirigeant sans blocage"], weight:2,type:'Interne' },
  { id:"3A2", starred:false, internal:true, title:"Fiches de poste", question:"Pour quels postes existe-t-il une fiche de poste écrite, et quand a-t-elle été mise à jour ?", relance:"Le titulaire du poste l'a-t-il lue ? Contient-elle des objectifs ?", besoinAcces:false, levels:["Aucune","Pour un ou deux postes","Pour tous, mais anciennes","Pour tous, à jour (moins d'un an)","À jour, avec objectifs et indicateurs, signées"], weight:2,type:'Interne' },
  { id:"3A3", starred:false, internal:true, title:"Accueil d'un nouvel arrivant", question:"Que se passe-t-il le premier jour, la première semaine et le premier mois d'un nouvel arrivant ?", relance:"Qui est son référent ? Quand fait-on le point de fin de période d'essai ?", besoinAcces:false, levels:["Aucun accueil","Présentation rapide le premier jour","Accompagnement informel la première semaine","Livret d'accueil et un référent","Parcours écrit sur 1 à 3 mois, point de fin de période"], weight:2,type:'Interne' },
  { id:"3A4", starred:false, internal:true, title:"Planning et remplacements", question:"Quand l'équipe connaît-elle son planning, et que se passe-t-il quand quelqu'un est absent ?", relance:"La dernière absence imprévue : qui a remplacé, avec quel préavis ?", besoinAcces:false, levels:["Géré au jour le jour","Planning à la semaine, absences subies","Planning mensuel, remplacements improvisés","Planning mensuel, remplaçants prévus","Planning à 2 mois, pics et absences planifiés, heures supplémentaires suivies"], weight:2,type:'Interne' },
  { id:"3A5", starred:true, internal:true, title:"Procédures", question:"Parmi vos procédures clés (arrivée, départ, réclamations), lesquelles sont écrites, et sont-elles appliquées ?", relance:"Montrez-moi la dernière version. Quand a-t-elle été relue ?", besoinAcces:false, levels:["Aucune","Quelques notes","Principales écrites, peu appliquées","Écrites et appliquées","Écrites, appliquées, vérifiées et mises à jour"], weight:3,type:'Interne' },
  { id:"3A6", starred:true, internal:true, title:"Outils de travail", question:"Pour traiter une réservation, de la demande à l'encaissement, combien de fois la même information est-elle saisie ou recopiée ?", relance:"Quel outil vous fait perdre le plus de temps ? Que paie-t-on sans l'utiliser ?", besoinAcces:true, levels:["Papier ou tableurs dispersés","Outils présents, information ressaisie à chaque étape","Outils présents, ressaisie sur 1 ou 2 étapes","Outils utilisés par tous, ressaisie rare","Outils intégrés, aucune ressaisie, coût maîtrisé, équipe formée"], weight:3,type:'Interne' },
  { id:"3A7", starred:false, internal:true, title:"Stabilité de l'équipe", question:"Combien de collaborateurs sont partis ces 24 derniers mois, et savez-vous pourquoi ?", relance:"Faites-vous un entretien annuel ? Existe-t-il un plan de formation ?", besoinAcces:false, levels:["Plus d'un tiers de l'équipe est parti en 2 ans","Environ un quart est parti","Un salarié sur dix est parti","Aucun départ en 2 ans","Aucun départ, entretien annuel et plan de formation"], weight:2,type:'Interne' },
  { id:"3B1", starred:false, internal:false, title:"Profils disponibles", question:"Quand vous recrutez (réception, étage, cuisine et saisonniers), combien de temps faut-il pour trouver un bon profil, et avez-vous des candidats en attente ?", relance:"Dernier recrutement : combien de semaines, combien de candidats ?", besoinAcces:false, levels:["Impossible","Très difficile, plusieurs mois","Difficile, 1 à 2 mois","Assez facile grâce à un réseau","Vivier actif (écoles, réseau), candidats en attente"], enjeu:2,type:'Opportunité' },
  { id:"3B2", starred:true, internal:false, title:"Attractivité face aux concurrents", question:"Face aux concurrents locaux, vos conditions de travail (salaire, horaires, ambiance, formation) vous font-elles gagner ou perdre des candidats et des collaborateurs ?", relance:"Qui est parti chez un concurrent ces 2 dernières années, et pourquoi ?", besoinAcces:false, levels:["Des départs vers les concurrents, conditions inférieures","Conditions inférieures, risque de départ","Conditions comparables","Conditions supérieures sur un point clé","Employeur recherché, candidatures spontanées"], enjeu:3,type:'Menace' },
  { id:"3B3", starred:false, internal:false, title:"Prestataires RH et outils", question:"Faites-vous appel à des prestataires (recrutement, formation, paie, logiciels), et les avez-vous comparés ou négociés ?", relance:"Quel prestataire pèse le plus dans vos coûts ? Quand l'avez-vous mis en concurrence ?", besoinAcces:false, levels:["Aucun, tout en interne","Un prestataire subi","Prestataires utilisés, jamais comparés","Comparés une fois","Comparés chaque année, conditions négociées"], enjeu:1,type:'Opportunité' },
  { id:"4A1", starred:true, internal:true, title:"Plus grosses charges", question:"Citez vos 5 plus grosses charges hors salaires, avec leur montant annuel.", relance:"Quelle charge a le plus augmenté en 2 ans ? Avez-vous les factures sous la main ?", besoinAcces:true, levels:["Non","Vaguement","Oui, montants approximatifs","Oui, montants annuels exacts","Oui, suivies chaque mois avec un budget"], weight:3,type:'Interne' },
  { id:"4A2", starred:true, internal:true, title:"Échéances des contrats", question:"Pour chacun de vos contrats principaux, connaissez-vous la date de renouvellement et la date limite de préavis ?", relance:"Quel contrat se renouvelle dans les 12 prochains mois ?", besoinAcces:true, levels:["Aucune","Quelques-unes","La plupart, non suivies","Toutes, listées","Calendrier avec rappel 3 mois avant le préavis"], weight:3,type:'Interne' },
  { id:"4A3", starred:true, internal:true, title:"Dernière comparaison", question:"Quand avez-vous mis en concurrence au moins 2 fournisseurs pour la dernière fois, et quelle économie en est sortie ?", relance:"Sur quel poste n'avez-vous jamais comparé ?", besoinAcces:true, levels:["Jamais","Il y a plus de 3 ans","Il y a 2 à 3 ans","Il y a 1 à 2 ans","Il y a moins d'un an, économie chiffrée"], weight:3,type:'Interne' },
  { id:"4A4", starred:true, internal:true, title:"Marge par activité", question:"Quelle marge dégage chaque centre de profit (hébergement, restauration, spa, événements), et quels sont votre taux d'occupation et votre prix moyen ?", relance:"Quelle activité vous coûte plus qu'elle ne rapporte ?", besoinAcces:false, levels:["Non","Marge globale seulement","Marge connue pour l'activité principale","Marge connue pour la plupart","Marge par activité suivie chaque trimestre"], weight:3,type:'Interne' },
  { id:"4A5", starred:true, internal:true, title:"Trésorerie", question:"Quel est votre solde de trésorerie prévu dans 3 mois, et comment le savez-vous ?", relance:"Quel mois est le plus tendu ? Quel est votre seuil de rentabilité mensuel ?", besoinAcces:false, levels:["Non, je regarde le solde de la banque","Bilan annuel seulement","Suivi irrégulier","Tableau mensuel","Tableau mensuel, prévision à 3-6 mois, seuil de rentabilité connu"], weight:3,type:'Interne' },
  { id:"4A6", starred:false, internal:true, title:"Achats", question:"Comment gérez-vous vos achats (approvisionnements F&amp;B) : planification, nombre de devis, prix négociés, pertes ?", relance:"Dernière commande : combien de devis ? Quelle part est perdue ou jetée ?", besoinAcces:false, levels:["Au coup par coup, sans suivi","Fournisseur habituel, prix jamais comparés","Prix comparés de temps en temps","Commandes planifiées, 2 à 3 devis","Commandes planifiées, prix négociés, pertes mesurées"], weight:2,type:'Interne' },
  { id:"4A7", starred:false, internal:true, title:"Entretien et investissements", question:"Avez-vous un plan d'entretien et d'investissement budgété sur 12 mois ? La dernière panne coûteuse était-elle prévisible ?", relance:"Quel équipement vous inquiète le plus ?", besoinAcces:false, levels:["Aucun, pannes subies","Besoins connus, aucun budget","Liste des besoins, budget partiel","Plan budgété","Plan budgété, maintenance préventive planifiée"], weight:2,type:'Interne' },
  { id:"4B1", starred:true, internal:false, title:"Prix du marché", question:"Pour vos 3 plus gros postes, savez-vous si vous payez plus cher que le marché, et de combien ?", relance:"Quel écart avez-vous déjà constaté sur un devis concurrent ?", besoinAcces:false, levels:["Aucune idée","Impression seulement","Quelques comparaisons","Écart chiffré sur les postes principaux","Économies obtenues et mesurées"], enjeu:3,type:'Opportunité' },
  { id:"4B2", starred:true, internal:false, title:"Hausse des coûts", question:"Si vos charges augmentent de 10 %, pouvez-vous ajuster vos prix, et en combien de temps ?", relance:"La dernière hausse de tarif : quand, de combien, quelle réaction ?", besoinAcces:false, levels:["Hausses subies, aucune marge","Hausses subies, marge faible","Hausses connues, parade partielle","Hausses anticipées, contrats sécurisés","Hausses anticipées, contrats longs, tarifs ajustés"], enjeu:3,type:'Menace' },
  { id:"4B3", starred:false, internal:false, title:"Partenaires financiers", question:"Avec quels partenaires financiers (banque, expert-comptable, centrales d'achat) travaillez-vous, et quelles conditions avez-vous négociées, quand ?", relance:"Quand avez-vous revu vos conditions bancaires pour la dernière fois ?", besoinAcces:false, levels:["Conditions subies","Conditions correctes, jamais négociées","Comparées une fois","Négociées","Négociées chaque année, avec conseils de pilotage"], enjeu:2,type:'Opportunité' },
];

export type { DiagnosticQuestion } from './diagnosticData';

export const TRANSPARENCE: string[] = ["Un compte-rendu vous est remis sous 48 h , utilisable sans aucun achat auprès d'ALLNEEDS.","ALLNEEDS propose aussi des offres (STARTER, PRO, PERFORMANCE, Accès). La recommandation peut être de ne rien acheter chez nous. La fiche d'adéquation, en dernière page, vous est montrée.","Vos documents servent uniquement à ce diagnostic, sont consultés par l'équipe ALLNEEDS concernée, conservés 90 jours si aucun contrat n'est signé, puis supprimés. Suppression anticipée sur simple demande.","Aucune promesse chiffrée avant analyse. Le diagnostic constate, il ne juge pas.","Case à cocher : ☐ cadre lu et accepté pa r le décideur. (Texte sur les données à faire valider par un conseil juridique avant la première utilisation.)"];
export const DOCUMENTS: string[] = ["Dernières factures télécom, internet et énergie","Polices d'assurance","Contrats de blanchisserie et de fournisseurs F&amp;B","Abonnements logiciels et plateformes, avec relevé des commissions sur 12 mois","Taux d'occupation mensuel des 12 derniers mois et grille tarifaire par saison","Liens du site et des pages en ligne (Google, Instagram, plateformes)","Pour tout doc ument : masquer toute donnée nominative avant remise."];
export const GARDE_FOUS: string[] = ["Ne demander aucune donnée confidentielle de clients ou d'invités.","Ne se prononcer ni sur le classement ni sur la conformité réglementaire de l'établissement.","Ne promettre aucun niveau de réservations avant analyse.","Pour les commissions et l'occupation, demander le relevé et noter le chiffre vu dans la colonne Commentaire.","Chaque note est justifiée dans la colonne Commentaire (exemple cité, chiffre donné, docume nt vu)."];
export const CHARGES_POSTES: string[] = ["Blanchisserie et linge","Fournisseurs F&B","Énergie","Télécom et internet","Logiciels et plateformes","Assurances","Maintenance","Autre"];

