import { useState, type FormEvent } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Building2, HeartPulse, KeyRound, PlusCircle, ShieldCheck, UserRoundCog, UsersRound } from 'lucide-react'
import { Badge, Button, Card, Checkbox, Field, Input, SectionHeading, Stat } from '@/components/ui'
import { SECTOR_LABEL, SECTOR_ORDER } from '@/data/catalog'
import { useDemo } from '@/store/store'
import type { Sector } from '@/types'

export const Route = createFileRoute('/admin/concierges')({ component: AdminConcierges })

function AdminConcierges() {
  const {state,dispatch}=useDemo()
  const [name,setName]=useState('')
  const [email,setEmail]=useState('')

  function create(event:FormEvent){event.preventDefault();if(!name.trim()||!email.includes('@'))return;dispatch({type:'CONCIERGE_CREATE',account:{id:`conc-${Date.now()}`,name:name.trim(),email:email.trim(),active:true,sectors:[],assignedOrgIds:[],createdOrgIds:[]}});setName('');setEmail('')}

  const activeConcierges=state.concierges.filter(account=>account.active).length
  const assignedCount=state.concierges.reduce((sum,account)=>sum+account.assignedOrgIds.length,0)
  const unlockedSaas=Object.values(state.saasAccessByOrg).filter(Boolean).length

  return <div className="container-app space-y-6 py-7">
    <SectionHeading eyebrow="Administration · accès" title="Équipe & périmètres" description="Affectez chaque entreprise à un concierge, limitez son périmètre et contrôlez séparément les accès aux espaces métier."/>

    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Concierges actifs" value={`${activeConcierges} / ${state.concierges.length}`} hint="Comptes autorisés à travailler" tone="brand"/><Stat label="Affectations entreprises" value={assignedCount} hint={`${state.orgs.length} entreprises dans le portefeuille`} tone="info"/><Stat label="Espaces métier ouverts" value={`${unlockedSaas} / ${state.orgs.length}`} hint="Décision distincte de l’accès concierge" tone="success"/></div>

    <Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-ink-100 px-5 py-4"><span className="rounded-xl bg-brand-50 p-2 text-brand-700"><UserRoundCog size={18}/></span><div><h2 className="font-semibold text-ink-950">Ajouter un concierge</h2><p className="mt-0.5 text-xs text-ink-500">Vous pourrez ensuite lui attribuer ses secteurs et entreprises.</p></div></div><form className="grid gap-3 p-5 md:grid-cols-[1fr_1fr_auto] md:items-end" onSubmit={create}><Field label="Nom complet" required><Input value={name} onChange={event=>setName(event.target.value)} placeholder="Prénom Nom" required/></Field><Field label="E-mail professionnel" required><Input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="nom@allneeds.ma" required/></Field><Button type="submit"><PlusCircle size={16}/>Créer le compte</Button></form></Card>

    {state.registrationProfile?<Card className="flex flex-wrap items-center justify-between gap-4 p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-brand-700" size={19}/><div><h2 className="font-semibold text-ink-950">Activation du nouveau compte client</h2><p className="mt-1 text-sm text-ink-600">{state.registrationProfile.orgName||'Nouvel établissement'} · {SECTOR_LABEL[state.registrationProfile.sector]} · rendez-vous {state.registrationProfile.appointmentDate||'à planifier'} {state.registrationProfile.appointmentSlot||''}</p></div></div><Checkbox checked={state.registrationProfile.activated} onChange={event=>dispatch({type:'REGISTRATION_ACTIVATION_SET',value:event.target.checked})} label={state.registrationProfile.activated?'Compte actif':'Activer le compte'}/></Card>:null}

    <section><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-700">Répartition du portefeuille</p><h2 className="mt-1 text-xl font-bold text-ink-950">Qui suit quelles entreprises ?</h2></div><span className="text-xs text-ink-500">L’entreprise n’est visible que si le secteur est également autorisé.</span></div><div className="grid gap-4 xl:grid-cols-2">{state.concierges.map(concierge=><Card key={concierge.id} className={`overflow-hidden ${!concierge.active?'opacity-70':''}`}><div className="flex flex-wrap items-start justify-between gap-3 border-b border-ink-100 p-4"><div className="flex items-start gap-3"><div className="rounded-xl bg-ink-950 p-2 text-white"><UsersRound size={17}/></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-ink-950">{concierge.name}</h3><Badge tone={concierge.active?'success':'neutral'}>{concierge.active?'Actif':'Suspendu'}</Badge></div><p className="mt-1 text-sm text-ink-600">{concierge.email}</p></div></div><Button size="sm" variant="outline" onClick={()=>dispatch({type:'CONCIERGE_TOGGLE',id:concierge.id})}>{concierge.active?'Suspendre l’accès':'Réactiver'}</Button></div>
        <div className="grid gap-3 p-4 sm:grid-cols-2"><div className="rounded-xl bg-ink-50 p-3"><span className="text-xs text-ink-500">Entreprises réellement visibles</span><strong className="mt-1 block text-lg text-ink-950">{concierge.assignedOrgIds.filter(id=>concierge.sectors.includes(state.orgs.find(org=>org.id===id)?.sector as Sector)).length}</strong></div><div className="rounded-xl bg-ink-50 p-3"><span className="text-xs text-ink-500">Secteurs autorisés</span><div className="mt-1 flex flex-wrap gap-1">{concierge.sectors.length?concierge.sectors.map(sector=><Badge key={sector} tone="neutral">{SECTOR_LABEL[sector]}</Badge>):<span className="text-sm font-medium text-amber-800">Aucun</span>}</div></div></div>
        <details className="border-t border-ink-100"><summary className="cursor-pointer px-4 py-3 text-sm font-semibold text-brand-700">Modifier ses accès & affectations</summary><div className="grid gap-5 border-t border-ink-100 bg-ink-50/40 p-4 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Secteurs autorisés</p><div className="mt-2 space-y-2">{SECTOR_ORDER.map(sector=><Checkbox key={sector} disabled={!concierge.active} checked={concierge.sectors.includes(sector)} onChange={event=>dispatch({type:'CONCIERGE_ASSIGN_SECTOR',id:concierge.id,sector,value:event.target.checked})} label={SECTOR_LABEL[sector]}/>)}</div></div><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Entreprises attribuées</p><div className="mt-2 space-y-2">{state.orgs.map(org=><label key={org.id} className={`flex items-center justify-between gap-3 rounded-lg border border-ink-100 bg-white px-3 py-2 ${!concierge.sectors.includes(org.sector)?'opacity-60':''}`}><Checkbox disabled={!concierge.active} checked={concierge.assignedOrgIds.includes(org.id)} onChange={event=>dispatch({type:'CONCIERGE_ASSIGN_ORG',id:concierge.id,orgId:org.id,value:event.target.checked})} label={org.name}/><span className="shrink-0 text-[.65rem] text-ink-500">{SECTOR_LABEL[org.sector]}</span></label>)}</div></div></div><p className="flex gap-2 border-t border-ink-100 px-4 py-3 text-xs leading-relaxed text-ink-500"><ShieldCheck size={14} className="shrink-0"/>Une entreprise attribuée hors des secteurs autorisés reste masquée. Suspendre le compte coupe l’accès sans supprimer l’historique.</p></details>
      </Card>)}</div>{state.concierges.length===0?<Card className="p-7 text-center text-sm text-ink-500">Aucun concierge. Créez le premier compte ci-dessus.</Card>:null}</section>

    <section><div className="mb-3 flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-700">Produit séparé</p><h2 className="mt-1 text-xl font-bold text-ink-950">Accès aux espaces métier SaaS</h2><p className="mt-1 text-sm text-ink-600">Ce réglage ouvre un espace métier pour l’entreprise cliente ; il ne modifie pas les droits des concierges.</p></div><Badge tone="neutral"><KeyRound size={12}/> Décision administrateur</Badge></div><div className="grid gap-3 xl:grid-cols-2">{state.orgs.map(org=>{const open=state.saasAccessByOrg[org.id]??false;const roles=state.saasRolesByOrg[org.id]??[];const activatedAt=state.saasActivatedAtByOrg[org.id];return <Card key={org.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-ink-950">{org.name}</h3><Badge tone="neutral">{SECTOR_LABEL[org.sector]}</Badge><Badge tone={open?'success':'neutral'}>{open?'Espace ouvert':'Espace fermé'}</Badge></div><p className="mt-1 text-xs text-ink-500">{org.kind} · {org.city}{open&&activatedAt?` · ouvert le ${new Date(activatedAt).toLocaleDateString('fr-FR')}`:''}</p></div><Checkbox checked={open} onChange={event=>dispatch({type:'SAAS_SET_ORG_ACCESS',orgId:org.id,value:event.target.checked})} label={open?'Autorisé':'Autoriser'}/></div>
        {org.sector==='sante'?<div className={`mt-3 rounded-xl border p-3 ${open?'border-sky-100 bg-sky-50/60':'border-ink-100 bg-ink-50 opacity-70'}`}><div className="flex items-center gap-2"><HeartPulse size={15} className="text-brand-700"/><p className="text-xs font-semibold text-ink-900">Rôles dans ALLNEEDS Santé</p></div><div className="mt-2 grid gap-2 sm:grid-cols-3">{([['directeur','Directeur'],['reception','Réception'],['comptabilite','Comptabilité']] as const).map(([role,label])=><Checkbox key={role} disabled={!open} checked={roles.includes(role)} onChange={event=>dispatch({type:'SAAS_SET_ORG_ROLE',orgId:org.id,role,value:event.target.checked})} label={label}/>)}</div></div>:<p className="mt-3 flex items-center gap-2 rounded-lg bg-ink-50 px-3 py-2 text-xs text-ink-500"><Building2 size={13}/>Les rôles de l’espace {SECTOR_LABEL[org.sector]} seront configurés lors de son ouverture.</p>}
      </Card>})}</div></section>
    <p className="text-xs text-ink-400">Mode démonstration : les comptes, affectations et autorisations sont enregistrés localement dans ce navigateur.</p>
  </div>
}
