import { Link, createFileRoute } from '@tanstack/react-router'
import type { ReactNode } from 'react'
import { ArrowRight, Banknote, Building2, CalendarClock, CheckCircle2, CircleAlert, FileCheck2, Handshake, Inbox, LineChart, Search, ShieldAlert, Target, UsersRound } from 'lucide-react'
import { useDemo } from '@/store/store'
import { PageHeader } from '@/components/layouts'
import { Badge, Button, Card, Stat } from '@/components/ui'
import { daysUntil, dateTime, longDate, money, relative } from '@/lib/format'
import { byId } from '@/lib/utils'
import { DEMO_NOW } from '@/data/demo'
import { ActivityPulse } from '@/components/ActivityPulse'

export const Route = createFileRoute('/admin/')({component:AdminOverview,head:()=>({meta:[{title:'Direction — ALLNEEDS'}]})})

type Priority={id:string;rank:number;type:string;title:string;org:string;detail:string;when:string;to:string;cta:string;level:'danger'|'warning'|'info'}

function AdminOverview(){
  const {state}=useDemo()
  const now=new Date(DEMO_NOW).getTime()
  const activeNeeds=state.needs.filter(need=>!['signe','clos'].includes(need.status))
  const activeMissions=state.missions.filter(mission=>mission.status!=='terminee')
  const activeLeads=state.leads.filter(lead=>!['gagne','perdu'].includes(lead.stage))
  const contracted=activeMissions.reduce((sum,mission)=>sum+mission.price,0)
  const pipeline=activeLeads.reduce((sum,lead)=>sum+(lead.budget??0),0)
  const priorities:Priority[]=[]

  state.requests.filter(request=>request.status==='nouveau').forEach(request=>priorities.push({id:`request-${request.id}`,rank:0,type:'DEMANDE À RÉPONDRE',title:`Répondre à ${request.name}`,org:request.org,detail:`Demande ${request.kind} reçue ${relative(request.at,now)} · ${request.message}`,when:request.at,to:'/admin/qualification',cta:'Traiter la demande',level:'danger'}))
  activeLeads.forEach(lead=>{const late=daysUntil(lead.nextActionAt,now);if(late<=3)priorities.push({id:`lead-${lead.id}`,rank:late<0?0:1,type:'PROSPECT · PROCHAINE ACTION',title:lead.nextAction,org:lead.orgName,detail:`${lead.contactName} · étape ${lead.stage} · ${late<0?`en retard de ${Math.abs(late)} j`:'à faire prochainement'}`,when:lead.nextActionAt,to:'/admin/relances',cta:'Préparer la relance',level:late<0?'danger':'warning'})})
  activeNeeds.forEach(need=>{const org=byId(state.orgs,need.orgId);const quoteCount=need.quoteIds.length;const providerCount=need.candidateIds.length;if(need.urgency==='haute'||providerCount===0||quoteCount===0)priorities.push({id:`need-${need.id}`,rank:need.urgency==='haute'?0:2,type:'BESOIN CLIENT',title:need.title,org:org?.name??'Entreprise',detail:`${need.urgency==='haute'?'Prioritaire · ':''}${providerCount} prestataire(s), ${quoteCount} devis · responsable ${need.assignedTo}`,when:need.deadline??need.submittedAt,to:'/admin/besoins/',cta:providerCount===0?'Trouver un prestataire':quoteCount===0?'Obtenir un devis':'Faire le point',level:need.urgency==='haute'?'danger':'warning'})})
  activeMissions.forEach(mission=>{const org=byId(state.orgs,mission.orgId);mission.milestones.filter(milestone=>milestone.status!=='fait'&&daysUntil(milestone.dueAt,now)<0).forEach(milestone=>priorities.push({id:`milestone-${mission.id}-${milestone.id}`,rank:0,type:'ENGAGEMENT EN RETARD',title:milestone.title,org:org?.name??'Entreprise',detail:`${mission.title} · responsable ${mission.owner} · échéance ${longDate(milestone.dueAt)}`,when:milestone.dueAt,to:'/admin/missions/',cta:'Replanifier et prévenir',level:'danger'}))})
  const retouches=state.deliverables.filter(item=>item.status==='retouche')
  retouches.forEach(item=>{const mission=state.missions.find(candidate=>candidate.id===item.missionId);const org=mission?byId(state.orgs,mission.orgId):undefined;if(mission)priorities.push({id:`retouche-${item.id}`,rank:0,type:'RETOUCHE CLIENT',title:item.title,org:org?.name??'Entreprise',detail:`${mission.title} · v${item.version}/${item.maxVersions} · responsable ${item.owner}`,when:item.updatedAt,to:'/admin/missions/',cta:'Relancer la production',level:'danger'})})
  state.diagnostics.filter(diagnostic=>diagnostic.status==='en_revue').forEach(diagnostic=>{const org=byId(state.orgs,diagnostic.orgId);priorities.push({id:`diagnostic-${diagnostic.id}`,rank:2,type:'DIAGNOSTIC À RESTITUER',title:`Relire ${diagnostic.ref}`,org:org?.name??'Entreprise',detail:`Diagnostic prêt depuis ${relative(diagnostic.createdAt,now)} · valider constats, confidentialité et priorités.`,when:diagnostic.createdAt,to:'/admin/diagnostics/',cta:'Relire le diagnostic',level:'info'})})
  const nextMeeting=state.meetings.filter(meeting=>meeting.status==='confirme'||meeting.status==='propose').sort((a,b)=>a.at.localeCompare(b.at))[0]
  const meetingOrg=nextMeeting?byId(state.orgs,nextMeeting.orgId):undefined
  const lateCount=priorities.filter(item=>item.rank===0).length
  priorities.sort((a,b)=>a.rank-b.rank||a.when.localeCompare(b.when))

  const deliveryIssues=activeMissions.reduce((sum,mission)=>sum+mission.milestones.filter(milestone=>milestone.status!=='fait'&&daysUntil(milestone.dueAt,now)<0).length,0)+retouches.length
  const needsWithoutProvider=activeNeeds.filter(need=>need.candidateIds.length===0).length
  const appointmentsWaiting=state.meetings.filter(meeting=>meeting.status==='propose').length

  return <>
    <PageHeader eyebrow="Direction · ALLNEEDS" title="Piloter l’activité" description="Les décisions qui protègent le client, la livraison et le chiffre d’affaires — dans l’ordre où elles demandent ton attention." actions={<Link to="/admin/clients"><Button size="sm" variant="outline"><Building2 size={14}/>Portefeuille clients<ArrowRight size={14}/></Button></Link>}/>

    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Honoraires des missions en cours" value={money(contracted)} hint={`${activeMissions.length} missions ouvertes · contrat, pas encaissement`} tone="brand"/><Stat label="Budgets des prospects ouverts" value={money(pipeline)} hint={`${activeLeads.length} opportunités · montants annoncés`} tone="info"/><Stat label="Engagements de livraison à risque" value={deliveryIssues} hint="Jalons en retard + retouches client" tone={deliveryIssues?'danger':'success'}/><Stat label="Besoins client sans prestataire" value={needsWithoutProvider} hint={`${activeNeeds.length} besoins actifs au total`} tone={needsWithoutProvider?'warning':'success'}/></div>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(330px,.75fr)]"><Card className="overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-ink-100 px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-700">File de décision</p><h2 className="mt-1 text-xl font-bold text-ink-950">Que faut-il régler aujourd’hui ?</h2><p className="mt-1 text-xs text-ink-500">Chaque ligne correspond à une entreprise et une action précise.</p></div><Badge tone={lateCount?'danger':'neutral'}>{priorities.length} sujets · {lateCount} urgents</Badge></header><div className="divide-y divide-ink-100">{priorities.slice(0,8).map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-4"><div className="flex min-w-0 items-start gap-3"><span className={`mt-0.5 rounded-lg p-2 ${item.level==='danger'?'bg-red-50 text-red-700':item.level==='warning'?'bg-amber-50 text-amber-700':'bg-sky-50 text-sky-700'}`}><CircleAlert size={16}/></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge tone={item.level}>{item.type}</Badge><span className="text-xs font-semibold text-ink-600">{item.org}</span></div><h3 className="mt-1 font-semibold leading-snug text-ink-950">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-ink-600">{item.detail}</p></div></div><Link to={item.to as any} className="ml-10 shrink-0 sm:ml-0"><Button size="sm" variant="outline">{item.cta}<ArrowRight size={14}/></Button></Link></article>)}{priorities.length===0?<div className="flex items-center gap-3 p-6"><CheckCircle2 className="text-emerald-700"/><div><p className="font-semibold text-ink-950">Aucun blocage repéré</p><p className="text-sm text-ink-600">La prochaine étape est de tenir le rendez-vous client ou de préparer le prochain jalon.</p></div></div>:null}{priorities.length>8?<Link to="/admin/relances" className="block bg-ink-50 px-5 py-3 text-sm font-semibold text-brand-700">Voir les {priorities.length-8} autres actions <ArrowRight className="inline" size={14}/></Link>:null}</div></Card>

    <div className="space-y-4"><Card className="overflow-hidden"><header className="border-b border-ink-100 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-700">Santé opérationnelle</p><h2 className="mt-1 text-lg font-bold text-ink-950">Où l’activité se bloque</h2></header><div className="space-y-1 p-3"><PulseRow icon={<Inbox size={16}/>} label="Demandes entrantes sans réponse" value={state.requests.filter(request=>request.status==='nouveau').length} to="/admin/qualification"/><PulseRow icon={<Search size={16}/>} label="Besoins sans prestataire" value={needsWithoutProvider} to="/admin/besoins/"/><PulseRow icon={<FileCheck2 size={16}/>} label="Livrables en attente du client" value={state.deliverables.filter(item=>item.status==='en_relecture').length} to="/admin/missions/"/><PulseRow icon={<Handshake size={16}/>} label="Rendez-vous à confirmer" value={appointmentsWaiting} to="/admin/relances"/></div></Card>

      {nextMeeting?<Card className="p-4"><div className="flex items-start gap-3"><span className="rounded-xl bg-brand-50 p-2 text-brand-700"><CalendarClock size={18}/></span><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Prochain engagement client</p><p className="mt-1 font-semibold text-ink-950">{nextMeeting.title}</p><p className="mt-1 text-xs text-ink-600">{meetingOrg?.name} · {dateTime(nextMeeting.at)} · {nextMeeting.status==='propose'?'créneau à confirmer':'confirmé'}</p></div></div></Card>:null}

      <Card className="border-amber-200 bg-amber-50/50 p-4"><div className="flex gap-2"><ShieldAlert size={17} className="mt-0.5 shrink-0 text-amber-800"/><div><p className="text-sm font-semibold text-amber-950">Ce que le tableau ne peut pas encore dire</p><p className="mt-1 text-xs leading-relaxed text-amber-900">La marge réelle, les factures encaissées, le coût des prestataires et le renouvellement client ne sont pas saisis. Le chiffre affiché correspond aux honoraires contractuels des missions ouvertes, pas à la trésorerie.</p></div></div></Card></div></div>

    <ActivityPulse activities={state.activities} title="Ce qui a changé dans l’activité" href="/admin/pipeline" />

    <details className="mt-6 rounded-2xl border border-ink-100 bg-white"><summary className="cursor-pointer list-none px-5 py-4 text-sm font-semibold text-ink-700">Ouvrir les outils de gestion détaillés <span className="ml-1 text-xs font-normal text-ink-500">Pipeline, quotas, équipe, diagnostics…</span></summary><div className="grid gap-3 border-t border-ink-100 p-4 sm:grid-cols-2 lg:grid-cols-4">{[{to:'/admin/pipeline',label:'Ventes & acquisition',detail:'Nouveaux prospects et signatures.',icon:<LineChart size={16}/>},{to:'/admin/clients',label:'Portefeuille clients',detail:'Situation et prochaine action par compte.',icon:<UsersRound size={16}/>},{to:'/admin/missions/',label:'Production des missions',detail:'Jalons, livrables et retours client.',icon:<Target size={16}/>},{to:'/admin/quotas',label:'Quotas & abonnements',detail:'Consommation et accès produit.',icon:<Banknote size={16}/>},{to:'/admin/besoins/',label:'Besoins & prestataires',detail:'Recherche, propositions et devis.',icon:<Search size={16}/>},{to:'/admin/diagnostics/',label:'Diagnostics',detail:'Relecture et restitution client.',icon:<FileCheck2 size={16}/>},{to:'/admin/concierges',label:'Équipe & affectations',detail:'Concierges et périmètres d’accès.',icon:<UsersRound size={16}/>},{to:'/admin/relances',label:'Relances',detail:'Contacts et prochaines échéances.',icon:<CalendarClock size={16}/> }].map(item=><Link key={item.to} to={item.to as any} className="rounded-xl border border-ink-100 p-4 transition hover:border-brand-200 hover:bg-brand-50/40"><div className="flex items-center gap-2 text-brand-700">{item.icon}<span className="text-sm font-semibold text-ink-950">{item.label}</span></div><p className="mt-1 text-xs text-ink-500">{item.detail}</p></Link>)}</div></details>
  </>
}

function PulseRow({icon,label,value,to}:{icon:ReactNode;label:string;value:number;to:string}){return <Link to={to as any} className="flex items-center gap-3 rounded-xl px-3 py-3 transition hover:bg-ink-50"><span className="text-ink-400">{icon}</span><span className="flex-1 text-sm text-ink-700">{label}</span><strong className={`tabular-nums ${value?'text-amber-800':'text-emerald-700'}`}>{value}</strong><ArrowRight size={14} className="text-ink-300"/></Link>}
