import { useMemo, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { AlarmClock, ArrowRight, ArrowUpRight, CalendarClock, Check, CheckCheck, ClipboardList, Mail, MessageCircle, Phone } from 'lucide-react'
import { useDemo } from '@/store/store'
import { PageHeader } from '@/components/layouts'
import { Badge, Button, Card, CardBody, CardHeader, EmptyState, Field, Input, Modal, Select, Tabs, Textarea, useDisclosure } from '@/components/ui'
import { MEETING_STATUS } from '@/lib/status'
import { dateTime, daysUntil, longDate, money, relative } from '@/lib/format'
import { byId } from '@/lib/utils'
import { Link } from '@tanstack/react-router'

export const Route = createFileRoute('/admin/relances')({ component: AdminRelances, head: () => ({ meta: [{ title: 'Relances — ALLNEEDS' }] }) })

type FollowUp = { id: string; kind: 'lead'|'document'|'quote'; orgId?: string; needId?: string; leadId?: string; title: string; body: string; due: string; tone: 'danger'|'warning'|'info'; contact: string; email: string; phone: string; subject: string; message: string; record?: (nextDate: string, note: string) => void }

export function AdminRelances() {
  const { state, dispatch } = useDemo()
  const modal = useDisclosure()
  const [filter, setFilter] = useState('toutes')
  const [selected, setSelected] = useState<FollowUp|null>(null)
  const [channel, setChannel] = useState<'email'|'telephone'>('email')
  const [nextDate, setNextDate] = useState('')
  const [note, setNote] = useState('')
  const now = Date.now()

  const items = useMemo<FollowUp[]>(() => {
    const leadItems: FollowUp[] = state.leads.filter((lead) => !['gagne','perdu'].includes(lead.stage)).map((lead) => {
      const left = daysUntil(lead.nextActionAt, now)
      return { id:`lead-${lead.id}`, kind:'lead', leadId:lead.id, title:lead.nextAction, body:`${lead.orgName} · ${lead.contactName} · étape ${lead.stage}`, due:left<0?`En retard de ${Math.abs(left)} j`:left===0?'À faire aujourd’hui':`Dans ${left} j · ${longDate(lead.nextActionAt)}`, tone:left<0?'danger':left<=3?'warning':'info', contact:lead.contactName, email:lead.email, phone:lead.phone, subject:`Suite à notre échange — ALLNEEDS`, message:`Bonjour ${lead.contactName},\n\nJe reviens vers vous au sujet de ${lead.orgName}. ${lead.nextAction}.\n\nQuel moment vous conviendrait pour en parler ?\n\nBien cordialement,\nL’équipe ALLNEEDS`, record:(date, detail)=>dispatch({type:'LEAD_PATCH',id:lead.id,patch:{lastContactAt:new Date(now).toISOString(),nextActionAt:new Date(`${date}T12:00:00`).toISOString(),nextAction:`Suivi après relance : ${detail || lead.nextAction}`,notes:[lead.notes,`[${new Date(now).toLocaleDateString('fr-FR')}] ${channel==='email'?'E-mail':'Appel'} — ${detail || 'contact tenté'}; prochain suivi ${date}`].filter(Boolean).join('\n')}}) }
    })
    const docItems: FollowUp[] = state.documents.filter((doc)=>doc.status==='demande').map((doc)=>{const org=byId(state.orgs,doc.orgId);return {id:`doc-${doc.id}`,kind:'document',orgId:doc.orgId,title:`Obtenir : ${doc.name}`,body:`${org?.name} · ${doc.required?'pièce requise':'pièce recommandée'} · ${doc.comment||'nécessaire pour poursuivre le dossier'}`,due:`Dernière mise à jour ${relative(doc.updatedAt,now)}`,tone:'warning',contact:org?.contactName??'Contact client',email:org?.contactEmail??'',phone:org?.contactPhone??'',subject:`Document attendu — ${doc.name}`,message:`Bonjour ${org?.contactName??''},\n\nPour faire avancer votre dossier, nous avons besoin de « ${doc.name} ». ${doc.comment}\n\nPouvez-vous nous l’envoyer ou nous indiquer quand il sera disponible ?\n\nBien cordialement,\nALLNEEDS`,record:(date,detail)=>dispatch({type:'DOC_SET_STATUS',id:doc.id,status:'demande',comment:`Relance ${new Date(now).toLocaleDateString('fr-FR')} : ${detail||'document demandé'} · prochain suivi ${date}`})}})
    const quoteItems: FollowUp[] = state.quotes.filter((quote)=>quote.status==='recu'||quote.status==='en_etude').map((quote)=>{const need=byId(state.needs,quote.needId);const org=byId(state.orgs,need?.orgId);return {id:`quote-${quote.id}`,kind:'quote',orgId:org?.id,needId:need?.id,title:`Obtenir une décision sur le devis · ${money(quote.amount)} DH`,body:`${org?.name} · ${need?.title} · validité jusqu’au ${longDate(quote.validUntil)}`,due:`Reçu ${relative(quote.receivedAt,now)} · échéance ${longDate(quote.validUntil)}`,tone:'info',contact:org?.contactName??'Contact client',email:org?.contactEmail??'',phone:org?.contactPhone??'',subject:`Votre devis pour ${need?.title}`,message:`Bonjour ${org?.contactName??''},\n\nAvez-vous pu examiner le devis de ${money(quote.amount)} DH concernant « ${need?.title} » ? Je peux répondre à vos questions ou organiser un point avec le prestataire.\n\nBien cordialement,\nALLNEEDS`}})
    return [...leadItems,...docItems,...quoteItems].sort((a,b)=>({danger:0,warning:1,info:2}[a.tone]-({danger:0,warning:1,info:2}[b.tone])))
  },[state.leads,state.documents,state.quotes,state.needs,state.orgs,now,dispatch,channel])

  const meetings = state.meetings.filter((meeting)=>meeting.status==='propose'||meeting.status==='confirme').sort((a,b)=>a.at.localeCompare(b.at))
  const due=items.filter((item)=>item.tone==='danger').length
  const soon=items.filter((item)=>item.tone==='warning').length

  function openFollowUp(item:FollowUp){setSelected(item);setChannel('email');setNextDate(new Date(now+3*86400000).toISOString().slice(0,10));setNote('');modal.open()}
  function beginContact(){if(!selected)return;if(channel==='email'){if(!selected.email)return;window.location.href=`mailto:${encodeURIComponent(selected.email)}?subject=${encodeURIComponent(selected.subject)}&body=${encodeURIComponent(selected.message)}`}else{if(!selected.phone)return;window.location.href=`tel:${selected.phone.replace(/\s/g,'')}`}}
  function saveFollowUp(){if(!selected||!nextDate)return;if(!selected.record){dispatch({type:'TOAST_ADD',toast:{title:'Suivi à enregistrer sur le besoin',description:'Le rappel devis est préparé. Ouvrez le besoin pour y consigner la réponse et la prochaine échéance.',tone:'warning'}});modal.close();return}selected.record(nextDate,note);dispatch({type:'TOAST_ADD',toast:{title:'Suivi enregistré',description:`${channel==='email'?'E-mail préparé / relance notée':'Appel tenté / relance notée'} · prochaine action le ${new Date(`${nextDate}T12:00:00`).toLocaleDateString('fr-FR')}`,tone:'success'}});modal.close()}

  const visible=items.filter(item=>filter==='toutes'||item.tone===filter)
  return <>
    <PageHeader eyebrow="Rigueur opérationnelle" title="Relances à effectuer" description="Une relance correspond à une personne, un motif et une prochaine date. Préparez le contact, puis consignez le résultat." />
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="À traiter aujourd’hui ou en retard" value={due} hint="Les plus urgentes sont en tête."/><StatCard label="À préparer" value={soon} hint="Documents et suivis proches."/><StatCard label="Rendez-vous à confirmer" value={meetings.filter(m=>m.status==='propose').length} hint="Un créneau proposé attend une réponse."/></div>
    <div className="mb-5"><Tabs value={filter} onChange={setFilter} tabs={[{value:'toutes',label:'À traiter',count:items.length},{value:'danger',label:'En retard'},{value:'warning',label:'À préparer'},{value:'info',label:'Suivis'}]}/></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader title="Votre prochaine action" description="Chaque bouton ouvre le bon canal et permet d’enregistrer la suite."/><div className="divide-y divide-ink-100">{visible.length===0?<CardBody><EmptyState title="Aucune relance à faire" description="La file est à jour. Revenez ici quand une échéance approche." icon={<CheckCheck className="h-5 w-5"/>}/></CardBody>:visible.map(item=><article key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><Badge tone={item.tone}>{item.due}</Badge><h3 className="mt-2 text-sm font-semibold text-ink-950">{item.title}</h3><p className="mt-1 text-xs text-ink-600">{item.body}</p><p className="mt-2 flex items-center gap-1.5 text-xs text-ink-500"><Phone size={13}/>{item.contact} · {item.phone||'Téléphone manquant'} <span className="px-1">·</span><Mail size={13}/>{item.email||'E-mail manquant'}</p></div><Button size="sm" onClick={()=>openFollowUp(item)}><MessageCircle size={14}/> Préparer le contact</Button></div></article>)}</div></Card>
    <div className="space-y-6"><Card><CardHeader title="Rendez-vous à confirmer" description="Un clic enregistre la confirmation dans le suivi."/><div className="divide-y divide-ink-100">{meetings.map(meeting=>{const org=byId(state.orgs,meeting.orgId);const status=MEETING_STATUS[meeting.status];return <article key={meeting.id} className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold">{meeting.title}</p><p className="mt-1 text-xs text-ink-500">{org?.name} · {dateTime(meeting.at)} · {meeting.location}</p></div><Badge tone={status.tone}>{status.label}</Badge></div>{meeting.status==='propose'?<Button size="sm" className="mt-3" onClick={()=>dispatch({type:'MEETING_SET_STATUS',id:meeting.id,status:'confirme'})}><Check size={14}/> Confirmer le créneau</Button>:null}</article>})}{meetings.length===0?<CardBody><p className="text-sm text-ink-500">Aucun rendez-vous en attente.</p></CardBody>:null}</div></Card>
    <Card className="p-5"><div className="flex items-center gap-2"><AlarmClock size={16}/><p className="text-sm font-semibold">Repères de suivi</p></div><ul className="mt-3 space-y-2 text-xs leading-relaxed text-ink-600"><li>• Un prospect : rappeler le besoin convenu et proposer un créneau.</li><li>• Un document manquant : préciser ce qu’il débloque et demander une date d’envoi.</li><li>• Un devis transmis : demander les questions et la décision avant son expiration.</li></ul><p className="mt-4 flex gap-2 border-t border-ink-100 pt-3 text-xs text-ink-500"><ClipboardList size={14}/>Le jeu de démonstration enregistre la note et la prochaine échéance localement. L’e-mail et l’appel sont ouverts dans vos applications.</p></Card></div></div>
    <Modal open={modal.open} onClose={modal.close} title="Préparer une relance" description={selected?`${selected.contact} · ${selected.body}`:''}><div className="space-y-4"><Field label="Canal"><Select value={channel} onChange={event=>setChannel(event.target.value as 'email'|'telephone')}><option value="email">E-mail</option><option value="telephone">Téléphone</option></Select></Field>{channel==='email'?<><Field label="Destinataire"><Input readOnly value={selected?.email||'Adresse e-mail manquante'}/></Field><Field label="Objet"><Input readOnly value={selected?.subject||''}/></Field><Field label="Message à envoyer"><Textarea rows={7} readOnly value={selected?.message||''}/></Field><Button variant="outline" disabled={!selected?.email} onClick={beginContact}><ArrowUpRight size={14}/> Ouvrir le brouillon e-mail</Button></>:<><p className="rounded-xl bg-ink-50 p-3 text-sm">Appelez <strong>{selected?.contact}</strong> au <strong>{selected?.phone||'numéro manquant'}</strong>, présentez le motif ci-dessous, puis notez sa réponse.</p><p className="rounded-xl border border-ink-100 p-3 text-sm text-ink-700">{selected?.message.split('\n').filter(Boolean).slice(1,3).join(' ')}</p><Button variant="outline" disabled={!selected?.phone} onClick={beginContact}><Phone size={14}/> Appeler</Button></>}<Field label="Résultat ou réponse"><Textarea rows={2} value={note} onChange={event=>setNote(event.target.value)} placeholder="Ex. échange réalisé, souhaite un rappel jeudi…"/></Field><Field label="Prochaine échéance"><Input type="date" min={new Date(now).toISOString().slice(0,10)} value={nextDate} onChange={event=>setNextDate(event.target.value)}/></Field><div className="flex justify-end gap-2"><Button variant="ghost" onClick={modal.close}>Annuler</Button>{selected?.record?<Button disabled={!nextDate} onClick={saveFollowUp}><CalendarClock size={14}/>Enregistrer le suivi</Button>:selected?.orgId?<Link to="/admin/besoins/$id" params={{id:selected.needId??''} as any} onClick={()=>modal.close()}><Button variant="primary"><ArrowRight size={14}/>Ouvrir le besoin</Button></Link>:<Button variant="outline" onClick={modal.close}>Fermer</Button>}</div><p className="text-xs text-ink-400">L’enregistrement consigne l’action et la prochaine date. Il ne prétend pas qu’un e-mail a été envoyé : vérifiez le brouillon dans votre messagerie. Pour un devis, consignez le rappel directement dans le besoin.</p></div></Modal>
  </>
}

function StatCard({label,value,hint}:{label:string;value:number;hint:string}){return <div className="rounded-xl border border-ink-100 bg-white p-4"><p className="text-[0.7rem] font-semibold uppercase tracking-wider text-ink-500">{label}</p><p className="mt-2 font-display text-3xl leading-none text-ink-950">{value}</p><p className="mt-2 text-xs text-ink-500">{hint}</p></div>}
