import { useMemo, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { ArrowRight, Check, FilePenLine, MapPin, ShieldAlert, ShieldCheck, Star, Target } from 'lucide-react'
import { useDemo } from '@/store/store'
import { PageHeader } from '@/components/layouts'
import { Badge, Button, Card, CardBody, CardHeader, Field, Input, Modal, Select, Stat, Tabs, Textarea, useDisclosure } from '@/components/ui'
import { SECTOR_LABEL } from '@/data/catalog'
import { longDate, money, relative } from '@/lib/format'
import { byId } from '@/lib/utils'
import { DEMO_NOW } from '@/data/demo'
import type { Provider } from '@/types'

export const Route = createFileRoute('/admin/prestataires/')({ component: AdminProviders, head: () => ({ meta: [{ title: 'Réseau prestataires — ALLNEEDS' }] }) })

export function AdminProviders() {
  const { state, dispatch } = useDemo()
  const [filter, setFilter] = useState('tous')
  const [category, setCategory] = useState('toutes')
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<Provider|null>(null)
  const [draft, setDraft] = useState<Provider|null>(null)
  const editModal = useDisclosure()
  const matchModal = useDisclosure()
  const now = new Date(DEMO_NOW).getTime()
  const categories = Array.from(new Set(state.providers.map(p=>p.category)))
  const providers = state.providers.filter(p=>(filter==='tous'||p.verification===filter)&&(category==='toutes'||p.category===category)&&(!query.trim()||`${p.name} ${p.categoryLabel} ${p.city}`.toLowerCase().includes(query.toLowerCase())))
  const eligible = state.providers.filter(p=>p.verification==='approfondie'&&p.insurance).length
  const needsByProvider = state.needs.reduce<Record<string,number>>((acc,need)=>{need.candidateIds.forEach(id=>{acc[id]=(acc[id]??0)+1});return acc},{})
  const quotesByProvider = state.quotes.reduce<Record<string,number>>((acc,quote)=>{acc[quote.providerId]=(acc[quote.providerId]??0)+1;return acc},{})
  const accepted = state.quotes.filter(quote=>quote.status==='accepte').length
  const acceptance = state.quotes.length?`${Math.round(accepted/state.quotes.length*100)} %`:'—'

  const compatibleNeeds = useMemo(()=>selected?state.needs.filter(need=>need.category===selected.category&&!['signe','clos'].includes(need.status)).sort((a,b)=>(b.urgency==='haute'?1:0)-(a.urgency==='haute'?1:0)||a.submittedAt.localeCompare(b.submittedAt)):[],[selected,state.needs])
  function openEdit(provider:Provider){setDraft({...provider});editModal.open()}
  function saveProvider(){if(!draft)return;dispatch({type:'PROVIDER_PATCH',id:draft.id,patch:draft});dispatch({type:'TOAST_ADD',toast:{title:'Dossier prestataire mis à jour',description:`${draft.name} · informations enregistrées sur cet appareil`,tone:'success'}});editModal.close()}
  function propose(needId:string){if(!selected)return;dispatch({type:'NEED_ADD_PROVIDER',needId,providerId:selected.id});dispatch({type:'TOAST_ADD',toast:{title:'Prestataire relié au besoin',description:`${selected.name} pourra être présenté au client après vérification de l’adéquation et des pièces.`,tone:'success'}})}

  return <>
    <PageHeader eyebrow="Réseau · pilotage" title="Prestataires" description="Entretenez les dossiers, repérez les pièces à confirmer et mobilisez le bon expert sur un besoin client." actions={<Badge tone="neutral">Réseau de démonstration</Badge>}/>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Réseau actif" value={state.providers.length} hint={`${categories.length} expertises représentées`} tone="brand"/><Stat label="Dossier approfondi + assurance" value={eligible} hint="À contrôler avant chaque mise en relation" tone="success"/><Stat label="Conformité public mineur" value={state.providers.filter(p=>p.minorsCompliant).length} hint="À confirmer pour les établissements concernés" tone="violet"/><Stat label="Devis acceptés" value={acceptance} hint={`${accepted} sur ${state.quotes.length} devis enregistrés`} tone="info"/></div>

    <Card className="mb-4 p-4"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_240px]"><Input aria-label="Rechercher un prestataire" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom, expertise, ville…"/><Select aria-label="Filtrer par expertise" value={category} onChange={e=>setCategory(e.target.value)}><option value="toutes">Toutes les expertises</option>{categories.map(cat=><option key={cat} value={cat}>{state.providers.find(p=>p.category===cat)?.categoryLabel??cat}</option>)}</Select></div></Card>
    <div className="mb-5"><Tabs value={filter} onChange={setFilter} tabs={[{value:'tous',label:'Tous',count:state.providers.length},{value:'approfondie',label:'Dossier approfondi',count:state.providers.filter(p=>p.verification==='approfondie').length},{value:'base',label:'À compléter',count:state.providers.filter(p=>p.verification==='base').length}]}/></div>

    <div className="grid gap-4 xl:grid-cols-2">{providers.map(provider=>{
      const providerNeeds=state.needs.filter(need=>need.candidateIds.includes(provider.id))
      const clientNames=Array.from(new Set(providerNeeds.map(need=>byId(state.orgs,need.orgId)?.name).filter((name):name is string=>Boolean(name))))
      const compatibleCount=state.needs.filter(need=>need.category===provider.category&&!['signe','clos'].includes(need.status)).length
      const hasGap=provider.verification!=='approfondie'||!provider.insurance
      return <Card key={provider.id} className="overflow-hidden"><CardHeader title={provider.name} description={`${provider.categoryLabel} · ${provider.city}`} action={<div className="flex items-center gap-2"><span className="flex items-center gap-1 text-sm font-semibold"><Star className="h-4 w-4 fill-amber-400 text-amber-400"/>{provider.rating.toFixed(1)}</span><Badge tone={provider.verification==='approfondie'?'success':'warning'}>{provider.verification==='approfondie'?'Dossier approfondi':'Dossier à compléter'}</Badge></div>}/>
        <CardBody className="space-y-4"><div className="flex flex-wrap gap-2"><Badge tone={provider.insurance?'success':'warning'}>{provider.insurance?'Assurance renseignée':'Assurance à vérifier'}</Badge><Badge tone={provider.minorsCompliant?'info':'neutral'}>{provider.minorsCompliant?'Public mineur : déclaré conforme':'Public mineur : non confirmé'}</Badge><Badge tone="neutral">Réponse {provider.responseDelay}</Badge><Badge tone="neutral">{provider.priceHint}</Badge></div>
          <div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Ce qui aide à choisir</p><p className="mt-1 text-sm leading-relaxed text-ink-700">{provider.highlights.join(' · ')}</p></div><div className="rounded-xl bg-ink-50 px-4 py-3 text-center"><span className="block text-xs text-ink-500">Besoins dans son expertise</span><strong className="font-display text-2xl text-ink-950">{compatibleCount}</strong></div></div>
          {hasGap?<div className="flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2.5 text-xs leading-relaxed text-amber-950"><ShieldAlert size={15} className="mt-0.5 shrink-0"/><span><strong>À confirmer avant de présenter :</strong> {provider.verification!=='approfondie'?'vérification des références et du dossier. ':''}{!provider.insurance?'assurance professionnelle.':''}Ce statut ne vaut pas validation des pièces.</span></div>:<div className="flex items-start gap-2 rounded-xl bg-emerald-50 px-3 py-2.5 text-xs text-emerald-900"><ShieldCheck size={15}/><span>Dossier déclaré approfondi et assurance renseignée · dernière vérification le {longDate(provider.verifiedAt)}. Confirmez la validité des justificatifs avant chaque proposition.</span></div>}
          <details className="rounded-xl border border-ink-100"><summary className="cursor-pointer px-3 py-2.5 text-sm font-semibold text-ink-700">Références, retour d’expérience et mobilisation</summary><div className="space-y-3 border-t border-ink-100 p-3"><p className="text-sm text-ink-700">{provider.note}</p><p className="text-xs text-ink-500"><strong>Références :</strong> {provider.references.join(' · ')||'À renseigner'}</p><div className="grid grid-cols-3 gap-2 text-center"><Metric label="Besoins proposés" value={needsByProvider[provider.id]??0}/><Metric label="Devis reçus" value={quotesByProvider[provider.id]??0}/><Metric label="Clients" value={clientNames.length}/></div>{clientNames.length?<p className="text-xs text-ink-500">Déjà mobilisé pour : {clientNames.join(', ')} · activité {relative(state.now,now)}</p>:<p className="text-xs text-ink-500">Pas encore proposé sur un besoin client.</p>}</div></details>
          <div className="flex flex-wrap justify-between gap-2 border-t border-ink-100 pt-3"><Button size="sm" variant="outline" onClick={()=>openEdit(provider)}><FilePenLine size={14}/>Mettre à jour le dossier</Button><Button size="sm" onClick={()=>{setSelected(provider);matchModal.open()}}><Target size={14}/>Besoins compatibles ({compatibleCount}) <ArrowRight size={14}/></Button></div>
        </CardBody></Card>
    })}{providers.length===0?<Card className="p-8 text-center xl:col-span-2"><p className="font-semibold text-ink-900">Aucun prestataire correspondant</p><p className="mt-1 text-sm text-ink-500">Modifiez la recherche ou les filtres.</p></Card>:null}</div>

    <Modal open={matchModal.open} onClose={matchModal.close} title={`Besoins compatibles · ${selected?.name??''}`} description="Même expertise. Vérifiez la ville, le budget et le niveau de conformité avant toute proposition client." size="lg"><div className="max-h-[65vh] space-y-3 overflow-y-auto">{compatibleNeeds.map(need=>{const org=byId(state.orgs,need.orgId);const alreadyAdded=need.candidateIds.includes(selected?.id??'');return <article key={need.id} className="rounded-xl border border-ink-100 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-ink-950">{need.title}</h3><p className="mt-1 text-sm text-ink-600">{org?.name} · {SECTOR_LABEL[org?.sector??'enseignement']} · <MapPin size={13} className="inline"/> {need.location}</p><p className="mt-2 text-xs text-ink-500">{need.description}</p><p className="mt-2 text-xs font-medium text-ink-700">Budget : {need.budgetMax?`jusqu’à ${money(need.budgetMax)}`:'à qualifier'} · Responsable : {need.assignedTo} · {need.urgency==='haute'?'Urgent':'Échéance'} {need.deadline?longDate(need.deadline):'à définir'}</p></div><div className="flex flex-col items-end gap-2"><Badge tone={need.urgency==='haute'?'danger':'neutral'}>{need.urgency==='haute'?'Prioritaire':'À traiter'}</Badge><Button size="sm" variant={alreadyAdded?'outline':'primary'} disabled={alreadyAdded} onClick={()=>propose(need.id)}>{alreadyAdded?<><Check size={14}/>Déjà relié</>:<>Relier au dossier <ArrowRight size={14}/></>}</Button></div></div></article>})}{compatibleNeeds.length===0?<div className="rounded-xl bg-ink-50 p-5 text-sm text-ink-600">Aucun besoin actif ne correspond à cette expertise pour le moment.</div>:null}<p className="flex gap-2 border-t border-ink-100 pt-3 text-xs text-ink-500"><ShieldAlert size={14} className="shrink-0"/>Relier au dossier ne transmet pas automatiquement le prestataire au client. La proposition doit être vérifiée puis envoyée depuis la fiche du besoin.</p></div></Modal>

    <Modal open={editModal.open} onClose={editModal.close} title={`Dossier prestataire · ${draft?.name??''}`} description="Actualisez uniquement des informations confirmées avec le prestataire." size="lg">{draft?<div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Ville"><Input value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></Field><Field label="Délai de réponse annoncé"><Input value={draft.responseDelay} onChange={e=>setDraft({...draft,responseDelay:e.target.value})}/></Field><Field label="Niveau du dossier"><Select value={draft.verification} onChange={e=>setDraft({...draft,verification:e.target.value as Provider['verification']})}><option value="base">À compléter</option><option value="approfondie">Approfondi (après vérification réelle)</option></Select></Field><Field label="Dernière date de vérification"><Input type="date" value={draft.verifiedAt.slice(0,10)} onChange={e=>setDraft({...draft,verifiedAt:new Date(`${e.target.value}T12:00:00`).toISOString()})}/></Field><Field label="Fourchette de prix"><Input value={draft.priceHint} onChange={e=>setDraft({...draft,priceHint:e.target.value})}/></Field><Field label="Conformité pour public mineur"><Select value={draft.minorsCompliant?'oui':'non'} onChange={e=>setDraft({...draft,minorsCompliant:e.target.value==='oui'})}><option value="non">Non confirmée</option><option value="oui">Confirmée sur pièce</option></Select></Field></div><label className="flex items-center gap-2 rounded-xl border border-ink-100 p-3 text-sm"><input type="checkbox" checked={draft.insurance} onChange={e=>setDraft({...draft,insurance:e.target.checked})} className="accent-brand-700"/>Attestation d’assurance professionnelle vérifiée</label><Field label="Points forts vérifiés" hint="Une ligne par élément"><Textarea rows={3} value={draft.highlights.join('\n')} onChange={e=>setDraft({...draft,highlights:e.target.value.split('\n').filter(Boolean)})}/></Field><Field label="Références / sites / justificatifs consultés" hint="Notez les sources consultées, pas seulement les affirmations"><Textarea rows={2} value={draft.references.join('\n')} onChange={e=>setDraft({...draft,references:e.target.value.split('\n').filter(Boolean)})}/></Field><Field label="Note interne"><Textarea rows={3} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></Field><div className="flex justify-end gap-2"><Button variant="ghost" onClick={editModal.close}>Annuler</Button><Button onClick={saveProvider}>Enregistrer les informations</Button></div><p className="text-xs text-ink-500">Démo : ces modifications sont enregistrées dans le navigateur. Le passage à « approfondi » ou la conformité mineurs doivent être appuyés par des justificatifs vérifiés.</p></div>:null}</Modal>
  </>
}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-lg bg-ink-50 p-2"><span className="block text-[.65rem] text-ink-500">{label}</span><strong className="text-base text-ink-950">{value}</strong></div>}
