import { Link, createFileRoute } from '@tanstack/react-router'
import { ArrowRight, Check, Clock3, FileCheck2, ShieldCheck } from 'lucide-react'

export const Route = createFileRoute('/_public/diagnostic')({
  component: DiagnosticPage,
  head: () => ({ meta: [
    { title: 'Le diagnostic ALLNEEDS — Faire le point, librement' },
    { name: 'description', content: 'Découvrez le déroulé du diagnostic offert ALLNEEDS : un échange guidé, trois priorités écrites et aucune obligation de poursuivre.' },
  ] }),
})

function DiagnosticPage() {
  return <div className="bg-white">
    <section className="relative isolate overflow-hidden bg-[#f8fbff]"><div aria-hidden="true" className="absolute inset-y-0 right-0 -z-10 w-1/2 bg-[radial-gradient(ellipse_at_80%_30%,#dfedff,transparent_70%)]"/><div className="container-page grid items-center gap-12 py-16 sm:py-20 lg:min-h-[500px] lg:grid-cols-[1fr_.8fr] lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">Le diagnostic ALLNEEDS</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-semibold leading-[1.08] tracking-[-.04em] sm:text-6xl">Vous avez déjà assez de sujets en tête. <span className="text-brand-700">Commençons par y voir clair.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink-600">Un temps cadré pour comprendre votre établissement, faire émerger l’essentiel et repartir avec un cap concret — sans devoir décider d’une mission aujourd’hui.</p><Link to="/inscription" className="mt-8 inline-flex min-h-14 items-center gap-2 rounded-full bg-brand-700 px-7 font-bold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-brand-800">Préparer mon diagnostic <ArrowRight className="h-4 w-4"/></Link><p className="mt-4 text-sm text-ink-500">Environ 2h15 · offert selon les conditions en vigueur · sans engagement</p></div><aside className="rounded-[1.75rem] border border-white bg-white p-7 shadow-[0_28px_80px_rgba(22,47,85,.10)]"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-50 text-brand-700"><Clock3 className="h-6 w-6"/></span><div><p className="text-sm font-semibold">Le temps pour faire le tri</p><p className="text-sm text-ink-500">Pas pour remplir un questionnaire seul.</p></div></div><div className="my-6 h-px bg-ink-100"/><div className="space-y-4">{[['Écouter','Comprendre votre contexte et vos échéances.'],['Examiner','Distinguer les faits, les forces et les frictions.'],['Prioriser','Valider ensemble trois sujets à traiter.']].map(([title,desc],i)=><div key={title} className="flex gap-4"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-bold ${i===2?'bg-brand-700 text-white':'bg-ink-100 text-ink-600'}`}>{i+1}</span><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm leading-6 text-ink-600">{desc}</p></div></div>)}</div></aside></div></section>
    <section className="container-page py-20 sm:py-24"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">Ce que vous obtenez</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">Une lecture utile. Pas un rapport qui dort.</h2><p className="mt-5 text-base leading-7 text-ink-600">La synthèse sert à guider une décision et le travail de votre équipe.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-3">{[{icon:FileCheck2,title:'Une photo de la situation',desc:'Les faits utiles et les points d’appui, résumés.'},{icon:ShieldCheck,title:'Des difficultés clarifiées',desc:'Les sujets à creuser, séparés des suppositions.'},{icon:Check,title:'Trois priorités',desc:'Les prochaines actions à valider avec vous.'}].map(({icon:Icon,title,desc})=><article key={title} className="rounded-[1.5rem] border border-ink-100 p-7"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-50 text-brand-700"><Icon className="h-5 w-5"/></span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-600">{desc}</p></article>)}</div></section>
    <section className="bg-[#f7f9fc] py-20 sm:py-24"><div className="container-page grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">Après le diagnostic</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight tracking-tight">Vous choisissez. Le rythme vous appartient.</h2><p className="mt-5 text-base leading-7 text-ink-600">Si une mission peut aider, ALLNEEDS présente une proposition complète, avec son prix, son périmètre et ses livrables. Vous pouvez l’accepter, la refuser ou prendre le temps d’y réfléchir.</p></div><div className="space-y-3">{[['Le diagnostic clarifie le besoin','Il ne déclenche aucune commande.'],['La proposition est détaillée','Vous savez ce qui sera fait, par qui, dans quel délai et à quel prix.'],['Le travail commence après votre accord','Pas de mission engagée sur la base d’une estimation implicite.']].map(([title,desc],i)=><div key={title} className="flex gap-4 rounded-2xl border border-ink-100 bg-white p-5"><span className="font-display text-xl font-semibold text-brand-700">0{i+1}</span><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm leading-6 text-ink-600">{desc}</p></div></div>)}</div></div></section>
    <section className="container-page py-20 sm:py-24"><div className="mx-auto max-w-3xl rounded-[2rem] bg-ink-950 px-7 py-10 text-center text-white sm:px-12 sm:py-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-300">Vous n’avez pas à tout préparer</p><h2 className="mt-4 font-display text-3xl font-semibold tracking-tight sm:text-4xl">Venez avec vos questions. On fera le tri ensemble.</h2><p className="mx-auto mt-4 max-w-xl text-base leading-7 text-ink-200">Quelques repères sur votre activité suffisent pour commencer. Les éléments sensibles ne sont pas nécessaires.</p><Link to="/inscription" className="mt-7 inline-flex min-h-14 items-center gap-2 rounded-full bg-white px-7 font-bold text-ink-950 transition hover:bg-brand-50">Choisir mon créneau <ArrowRight className="h-4 w-4"/></Link></div></section>
  </div>
}
