import { useEffect, useState } from 'react'
import { Link } from '@tanstack/react-router'
import { useDemo } from '@/store/store'
import { syncAgencyCancellation, branches, tourismModules, initialTourism, enrich, validateTourism, type Branch, type TourismData, type BranchData, type TModule } from './tourism-model'
import { type Row } from './model'
import { Restaurant } from './Workspace'
import { RestaurantOperations, AgencyBuilder, SupplierRequests } from './TourismOperations'
import './workspace.css'
import './tourism.css'
export const money=(n:number)=>new Intl.NumberFormat('fr-MA',{style:'currency',currency:'MAD'}).format(n)
export function Tourism({branch:initial}:{branch?:Branch}){
 const {user}=useDemo();const org=String((user as {orgId?:string})?.orgId||'demo')
 return <TourismWorkspace key={org} org={org} initial={initial}/>
}
function TourismWorkspace({org,initial}:{org:string;initial?:Branch}){
 const key=`allneeds.tourism.v2.${org}`
 const [all,setAll]=useState<TourismData>(()=>{try{const raw=JSON.parse(localStorage.getItem(key)||'null');return raw&&raw.hebergement?.rows&&raw.agence?.rows?raw:initialTourism()}catch{return initialTourism()}})
 const [branch,setBranch]=useState<Branch>(initial||'agence');const [tab,setTab]=useState('overview');const [notice,setNotice]=useState('');const [clientView,setClientView]=useState(false)
 const data=all[branch]
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(all));window.dispatchEvent(new Event('allneeds-tourism-updated'))}catch{setNotice('Stockage du navigateur plein ou indisponible : exportez votre travail avant fermeture.')}},[all,key])
 useEffect(()=>{if(initial){setBranch(initial);setTab('overview')}},[initial])
 const change=(next:Branch)=>{setBranch(next);setTab('overview');setNotice('');setClientView(false)}
 const update=(next:BranchData)=>setAll(branch==='agence'?syncAgencyCancellation(all,next):{...all,[branch]:next})
 const config=tourismModules[branch];const module=config.find(m=>m.id===tab)
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:2,org,branch,data},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`allneeds-${branch}.json`;a.click();URL.revokeObjectURL(url)}
 const extra=branch==='restauration'?[['stock','Ingrédients & stock'],['recipes','Fiches techniques & prix'],['inventory','Achats, pertes & inventaires'],['orders','Commandes & cuisine'],['sales','Ventes de portions']]:branch==='agence'?[['builder','Packages, devis & vouchers']]:[]
 return <div className="saas tourism" style={{'--branch-accent':branches[branch].accent} as React.CSSProperties}>
 <header className="saas-hero"><span className="saas-kicker">ALLNEEDS TOURISME · {branches[branch].title.toUpperCase()}</span><h1>{branch==='agence'?'Un voyage cohérent. Chaque prestation sous contrôle.':branches[branch].subtitle+'.'}</h1><p>Un espace opérationnel dédié, avec ses clients, son planning, ses ressources et ses finances.</p><div className="tourism-branches">{(Object.keys(branches) as Branch[]).map(b=><button key={b} onClick={()=>change(b)} aria-pressed={b===branch}><span>{branches[b].icon}</span><strong>{branches[b].title}</strong><small>{branches[b].subtitle}</small></button>)}</div></header>
 <p className="saas-notice">Démo frontend · données fictives. Espaces métier séparés dans le navigateur, sans authentification ou synchronisation serveur.</p>
 <div className="saas-toolbar"><strong>{branches[branch].title}</strong><div><Link to="/app/diagnostic-auto">Diagnostic</Link><Link to="/app/tourisme/$branch" params={{branch}}>Lien direct de cette branche</Link><button onClick={exportData}>Exporter cet espace</button><button onClick={()=>setTab('calendar')}>Planning</button></div></div>
 <div className="saas-body"><nav className="saas-nav" aria-label="Navigation de la branche"><button aria-current={tab==='overview'?'page':undefined} onClick={()=>setTab('overview')}>Tableau de bord</button>{branch!=='agence'&&<button aria-current={tab==='requests'?'page':undefined} onClick={()=>setTab('requests')}>Demandes agence</button>}<button aria-current={tab==='calendar'?'page':undefined} onClick={()=>setTab('calendar')}>Planning central</button>{extra.map(([id,title])=><button key={id} onClick={()=>{setTab(id);setNotice('')}} aria-current={tab===id?'page':undefined}>{title}</button>)}{config.map(m=><button key={m.id} onClick={()=>{setTab(m.id);setNotice('')}} aria-current={tab===m.id?'page':undefined}>{m.title}<small>{data.rows[m.id]?.length||0}</small></button>)}</nav>
 <main className="saas-content">{notice&&<div className="saas-alert" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Fermer le message">×</button></div>}
 {tab==='overview'&&<Overview branch={branch} data={data} setTab={setTab}/>}
 {tab==='requests'&&branch!=='agence'&&<SupplierRequests branch={branch} all={all} setAll={setAll} notify={setNotice}/>}
 {tab==='calendar'&&<Calendar branch={branch} data={data}/>}
 {module&&<Records key={branch+module.id} branch={branch} module={module} data={data} update={update} notify={setNotice}/>}
 {branch==='restauration'&&['stock','recipes','sales'].includes(tab)&&<Restaurant key={tab} tab={tab} ws={data} setWs={next=>{const changes=next.ingredients.map(i=>({id:crypto.randomUUID(),ingredient:i.id,quantity:i.stock-(data.ingredients.find(x=>x.id===i.id)?.stock??i.stock),kind:'Gestion stock / vente',date:new Date().toISOString(),note:'Module ingrédients ou vente de portions',cost:i.cost})).filter(m=>m.quantity!==0);update({...data,...next,movements:[...data.movements,...changes]})}} setNotice={setNotice}/>}
 {branch==='restauration'&&['orders','inventory'].includes(tab)&&<RestaurantOperations tab={tab} data={data} update={update} notify={setNotice}/>}
 {branch==='agence'&&tab==='builder'&&<AgencyBuilder all={all} setAll={setAll} notify={setNotice} clientView={clientView} setClientView={setClientView}/>}
 </main></div></div>
}
function Overview({branch,data,setTab}:{branch:Branch;data:BranchData;setTab:(s:string)=>void}){
 const invoices=data.rows.paiements||[];const income=invoices.reduce((n,r)=>n+Number(r.paid||0),0);const due=invoices.reduce((n,r)=>n+Number(r.total||0)-Number(r.paid||0),0)
 const operations=branch==='hebergement'?data.rows.reservations:branch==='activites'?data.rows.participants:branch==='transport'?data.rows.trajets:branch==='agence'?data.rows.voyages:[]
 const today=new Date().toISOString().slice(0,10)
 const occupied=data.rows.reservations?.filter(r=>r.date<=today&&r.endDate>today&&!['Annulée','Parti'].includes(r.status)).length||0
 const cards=[['Opérations / dossiers',String(operations.length)],['Règlements factures',money(income)],['Solde factures',money(due)],branch==='hebergement'?['Occupation aujourd’hui',`${occupied} / ${data.rows.unites.length} unités`]:branch==='restauration'?['Tickets ouverts',String(data.tickets.filter(t=>!['Servie','Annulée'].includes(t.status)).length)]:branch==='activites'?['Créneaux ouverts',String(data.rows.sessions.filter(s=>s.status==='Ouverte').length)]:branch==='transport'?['Véhicules disponibles',String(data.rows.vehicules.filter(v=>v.status==='Disponible').length)]:['Prestations à confirmer',String(data.rows.prestations.filter(s=>['À demander','Demande envoyée','Option'].includes(s.status)).length)]]
 return <><h2>Votre tableau de bord {branches[branch].title.toLowerCase()}</h2><p className="saas-muted">Indicateurs issus de vos enregistrements. Les montants des opérations et des factures sont suivis séparément pour éviter de les compter deux fois.</p><div className="saas-stats">{cards.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="tourism-shortcuts">{tourismModules[branch].map(m=><button key={m.id} onClick={()=>setTab(m.id)}><strong>{m.title}</strong><p>{m.description}</p><span>{data.rows[m.id].length} fiches · Ouvrir →</span></button>)}</div><div className="saas-panel"><h3>Points de vigilance</h3>{branch==='restauration'&&<p>{data.ingredients.filter(i=>i.stock<=i.threshold).length} ingrédients sous le seuil de réapprovisionnement.</p>}<p>{invoices.filter(r=>r.date<today&&Number(r.paid)<Number(r.total)).length} échéances de facture dépassées.</p><p>{(data.rows.documents||[]).filter(r=>r.date<today&&r.status!=='Archivé').length} documents dont la date de validité est passée.</p>{branch==='transport'&&<p>{data.rows.chauffeurs.filter(r=>r.date<today).length} permis à renouveler.</p>}</div></>
}
function Records({branch,module,data,update,notify}:{branch:Branch;module:TModule;data:BranchData;update:(d:BranchData)=>void;notify:(s:string)=>void}){
 const [edit,setEdit]=useState<Row|null>(null);const [search,setSearch]=useState('');const [status,setStatus]=useState('')
 const rows=data.rows[module.id]||[]
 const label=(ref:string,id:string)=>data.rows[ref]?.find(r=>r.id===id)?.name||data.rows[ref]?.find(r=>r.id===id)?.client||id
 const derived=module.id==='clotures'?['difference']:branch==='transport'&&module.id==='trajets'?['total','cost']:branch==='agence'&&module.id==='prestations'?['total','totalCost']:['reservations','participants'].includes(module.id)&&branch!=='restauration'?['total']:[]
 const names:Record<string,string>={total:'Total (MAD)',cost:'Coût estimatif (MAD)',totalCost:'Coût fournisseur (MAD)',difference:'Écart de caisse (MAD)'}
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);let row:Row={...edit,id:edit?.id||crypto.randomUUID()};module.fields.forEach(f=>row[f.key]=String(form.get(f.key)||'').trim());row=enrich(branch,module.id,row,data);const error=validateTourism(branch,module.id,row,data);if(error){notify(error);return}update({...data,rows:{...data.rows,[module.id]:[...rows.filter(r=>r.id!==row.id),row]}});setEdit(null);notify('Fiche enregistrée.');e.currentTarget.reset()}
 function remove(row:Row){
 if(module.id==='prestations' && row.status==='Confirmée'){notify('Annulez cette prestation avant toute suppression, afin de libérer sa réservation fournisseur.');return}
 const referenced=tourismModules[branch].some(m=>m.fields.some(f=>f.ref===module.id&&(data.rows[m.id]||[]).some(r=>r[f.key]===row.id)))
 if(referenced){notify('Cette fiche est utilisée dans un autre module. Modifiez son statut plutôt que de la supprimer.');return}
 if(confirm('Supprimer cette fiche de démonstration ?'))update({...data,rows:{...data.rows,[module.id]:rows.filter(r=>r.id!==row.id)}})
 }
 function exportCsv(){const fields=[...module.fields.map(f=>f.key),...derived];const escape=(s:string)=>'"'+s.replace(/"/g,'""')+'"';const csv=[fields.map(escape).join(';'),...rows.map(r=>fields.map(f=>escape(/^[=+@\-]/.test(r[f]||'')?"'"+r[f]:r[f]||'')).join(';'))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=module.id+'.csv';a.click();URL.revokeObjectURL(url)}
 return <><div className="saas-toolbar"><h2>{module.title}</h2><button onClick={exportCsv}>Export CSV</button></div><p className="saas-muted">{module.description}</p><div className="saas-panel"><h3>{edit?'Modifier la fiche':'Nouvelle fiche'}</h3><form className="saas-form" key={edit?.id||module.id} onSubmit={submit}>{module.fields.map(f=><label key={f.key}>{f.label}{f.ref?<select name={f.key} required={f.required} defaultValue={edit?.[f.key]||''}><option value="">Choisir…</option>{(data.rows[f.ref]||[]).map(r=><option key={r.id} value={r.id}>{r.name||r.client||r.id}</option>)}</select>:f.options?<select name={f.key} defaultValue={edit?.[f.key]||f.options[0]}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:<input name={f.key} type={f.type||'text'} required={f.required} defaultValue={edit?.[f.key]||''} min={f.type==='number'?0:undefined} step={f.type==='number'?'any':undefined}/>}</label>)}<div className="saas-form-actions"><button className="saas-primary">Enregistrer</button>{edit&&<button type="button" onClick={()=>setEdit(null)}>Annuler</button>}</div></form></div><div className="tourism-filters"><input aria-label="Rechercher les fiches" placeholder="Rechercher…" value={search} onChange={e=>setSearch(e.target.value)}/>{module.fields.find(f=>f.key==='status')?.options&&<select aria-label="Filtrer le statut" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option>{module.fields.find(f=>f.key==='status')!.options!.map(s=><option key={s}>{s}</option>)}</select>}</div><div className="saas-table-wrap"><table><thead><tr>{module.fields.map(f=><th key={f.key}>{f.label}</th>)}{derived.map(d=><th key={d}>{names[d]}</th>)}<th>Actions</th></tr></thead><tbody>{rows.filter(r=>(!status||r.status===status)&&[...Object.values(r),...module.fields.filter(f=>f.ref).map(f=>label(f.ref!,r[f.key]))].some(v=>v.toLowerCase().includes(search.toLowerCase()))).map(row=><tr key={row.id}>{module.fields.map(f=><td key={f.key}>{f.ref?label(f.ref,row[f.key]):row[f.key]}</td>)}{derived.map(d=><td key={d}>{money(Number(row[d]||0))}</td>)}<td><button onClick={()=>setEdit(row)}>Modifier</button><button onClick={()=>remove(row)}>Supprimer</button></td></tr>)}</tbody></table>{!rows.length&&<p className="saas-empty">Aucune fiche. Créez les ressources de référence avant de réserver.</p>}</div></>
}
function Calendar({branch,data}:{branch:Branch;data:BranchData}){
 const [date,setDate]=useState(new Date().toISOString().slice(0,10))
 const ids=branch==='hebergement'?['reservations','menage']:branch==='restauration'?['reservations']:branch==='activites'?['sessions']:branch==='transport'?['trajets']:['prestations']
 const events=ids.flatMap(id=>(data.rows[id]||[]).filter(r=>r.date===date||(r.endDate&&r.date<=date&&r.endDate>date)).map((r):Row=>({...r,module:id}))).filter(r=>!['Annulée','Annulé','Refusée'].includes(r.status)).sort((a,b)=>(a.start||'').localeCompare(b.start||''))
 const text=(id:string)=>Object.values(data.rows).flat().find(r=>r.id===id)?.name||id
 return <><h2>Planning {branches[branch].title.toLowerCase()}</h2><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="tourism-timeline">{events.map(e=><article key={e.module+e.id}><time>{e.start||'Séjour'} {e.end?'– '+e.end:''}</time><div><h3>{e.name||text(e.client||'')}</h3><p>{text(e.unit||e.table||e.activity||e.vehicle||e.trip||'')} · {e.status}</p>{e.endDate&&<p>{e.date} → {e.endDate}</p>}</div></article>)}</div>{!events.length&&<div className="saas-panel">Aucune opération pour cette date.</div>}</>
}
