import { useEffect, useState } from 'react'
import { Link } from '@tanstack/react-router'
import { LockKeyhole } from 'lucide-react'
import { orgHasSaasAccess, useDemo } from '@/store/store'
import { modules, seed, titles, validateRow, recipeCost, sell, type Industry, type Row, type Workspace as Data, type Recipe } from './model'
import './workspace.css'
import { Tourism } from './Tourism'
const money=(n:number)=>new Intl.NumberFormat('fr-MA',{style:'currency',currency:'MAD'}).format(n)
export function Workspace(){
 const { user,state }=useDemo()
 const [tab,setTab]=useState('overview')
 const org=state.orgs.find(item=>item.id===user.orgId)
 const industry=(org?.sector||'sante') as Industry
 const orgKey=String(user.orgId||'demo')
 const accessGranted=org ? orgHasSaasAccess(state, org.id, org.sector) : false
 if(!accessGranted)return <div className="saas"><header className="saas-hero"><span className="saas-kicker">ALLNEEDS · {industry==='sante'?'SANTÉ':industry==='tourisme'?'TOURISME':'ENSEIGNEMENT'}</span><h1>{org?.name||'Votre établissement'}<br/>Votre espace métier.</h1><p>L’espace SaaS correspondant à votre secteur est visible dans votre compte, mais reste verrouillé jusqu’à validation par ALLNEEDS.</p></header><section className="saas-panel" style={{maxWidth:760,margin:'2rem auto'}}><div style={{display:'flex',gap:'1rem',alignItems:'flex-start'}}><span style={{display:'grid',placeItems:'center',width:48,height:48,borderRadius:14,background:'#eef2f4'}}><LockKeyhole size={22}/></span><div><h2 style={{marginTop:0}}>Accès SaaS en attente de validation</h2><p className="saas-muted">Votre secteur est bien enregistré : <strong>{industry==='sante'?'Santé':industry==='tourisme'?'Tourisme':'Enseignement'}</strong>. Les outils ne sont pas cliquables tant que l’administrateur n’a pas activé l’accès de votre entreprise.</p><p className="saas-muted">Vous pouvez continuer à utiliser vos besoins, diagnostics, missions, documents et rendez-vous depuis le menu.</p></div></div></section></div>
 if(industry==='tourisme')return <div className="saas"><header className="saas-hero"><span className="saas-kicker">ALLNEEDS · TOURISME</span><h1>{org?.name||'Votre établissement'}<br/>Votre espace métier.</h1><p>Réservations, hébergement, restauration, activités, transport et agence : uniquement les outils correspondant à votre entreprise.</p></header><Tourism/></div>
 return <div className="saas"><header className="saas-hero"><span className="saas-kicker">ALLNEEDS · {industry==='sante'?'SANTÉ':'ENSEIGNEMENT'}</span><h1>{org?.name||'Votre établissement'}<br/>Votre espace métier.</h1><p>{industry==='sante'?'Patients, rendez-vous, équipe, paiements et charges.':'Inscriptions, élèves, équipe, paiements et organisation.'} Aucun autre secteur n’est affiché dans votre compte.</p></header><WorkspaceBody key={orgKey+industry} industry={industry} org={orgKey} tab={tab} setTab={setTab}/></div>
}

function WorkspaceBody({industry,org,tab,setTab}:{industry:Industry;org:string;tab:string;setTab:(s:string)=>void}){
 const storageKey=`allneeds.saas.v1.${org}.${industry}`
 const [ws,setWs]=useState<Data>(()=>{try{const d=JSON.parse(localStorage.getItem(storageKey)||'null');return d&&d.rows&&Array.isArray(d.recipes)?d:seed(industry)}catch{return seed(industry)}})
 const [notice,setNotice]=useState('')
 const [search,setSearch]=useState('')
 const [edit,setEdit]=useState<Row|null>(null)
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(ws))}catch{setNotice('Sauvegarde indisponible. Exportez vos données avant de fermer.')}},[ws,storageKey])
 const config=modules[industry]
 const current=config.find(m=>m.id===tab)
 const payments=ws.rows.paiements||[]
 const due=payments.reduce((s,r)=>s+Number(r.total)-Number(r.paid),0)
 const received=payments.reduce((s,r)=>s+Number(r.paid),0)
 function saveRow(event:React.FormEvent<HTMLFormElement>){
 event.preventDefault(); if(!current)return
 const form=new FormData(event.currentTarget)
 const row:Row={id:edit?.id||crypto.randomUUID()}
 current.fields.forEach(f=>{row[f.key]=String(form.get(f.key)||'').trim()})
 const error=validateRow(tab,row,ws)
 if(error){setNotice(error);return}
 setWs({...ws,rows:{...ws.rows,[tab]:[...(ws.rows[tab]||[]).filter(r=>r.id!==row.id),row]}});setEdit(null);setNotice('Enregistrement sauvegardé.');event.currentTarget.reset()
 }
 function exportData(){const blob=new Blob([JSON.stringify({industry,workspace:ws},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`allneeds-${industry}.json`;a.click();URL.revokeObjectURL(url)}
 return <><div className="saas-toolbar"><strong>Espace {titles[industry]}</strong><div><Link to="/app/diagnostic-auto">Faire mon diagnostic →</Link><button onClick={exportData}>Exporter les données</button></div></div><div className="saas-body"><nav className="saas-nav" aria-label="Modules métier"><button aria-current={tab==='overview'?'page':undefined} onClick={()=>setTab('overview')}>Vue d’ensemble</button>{config.map(m=><button key={m.id} aria-current={tab===m.id?'page':undefined} onClick={()=>{setTab(m.id);setEdit(null);setSearch('');setNotice('')}}>{m.title}<small>{ws.rows[m.id]?.length||0}</small></button>)}{industry==='tourisme'&&<><button aria-current={tab==='stock'?'page':undefined} onClick={()=>setTab('stock')}>Ingrédients & stock</button><button aria-current={tab==='recipes'?'page':undefined} onClick={()=>setTab('recipes')}>Recettes & prix de vente</button><button aria-current={tab==='sales'?'page':undefined} onClick={()=>setTab('sales')}>Commandes & ventes</button></>}</nav><main className="saas-content">{notice&&<div role="status" className="saas-alert">{notice}<button aria-label="Fermer" onClick={()=>setNotice('')}>×</button></div>}
 {tab==='overview'&&<><h2>Votre activité en un regard</h2><p className="saas-muted">Les indicateurs se mettent à jour au fil de vos opérations.</p><div className="saas-stats"><article><span>Dossiers & opérations</span><strong>{Object.values(ws.rows).reduce((n,r)=>n+r.length,0)}</strong></article><article><span>Règlements enregistrés</span><strong>{money(received)}</strong></article><article><span>Reste à encaisser</span><strong>{money(due)}</strong></article>{industry==='tourisme'&&<article><span>Ventes restauration</span><strong>{money(ws.sales.reduce((n,r)=>n+r.total,0))}</strong></article>}</div><div className="saas-module-grid">{config.map(m=><button key={m.id} onClick={()=>setTab(m.id)}><span>{m.title}</span><p>{m.description}</p><strong>Ouvrir le module →</strong></button>)}</div>{industry==='tourisme'&&<div className="saas-panel"><h3>Vigilance stock</h3>{ws.ingredients.filter(i=>i.stock<=i.threshold).length?ws.ingredients.filter(i=>i.stock<=i.threshold).map(i=><p key={i.id}>{i.name} : {i.stock.toFixed(2)} {i.unit} · réapprovisionnement nécessaire</p>):<p>Aucun ingrédient sous le seuil d’alerte.</p>}<p className="saas-muted">Marge ingrédients réalisée : {money(ws.sales.reduce((n,r)=>n+r.total-r.cost,0))}. Hors personnel, énergie, pertes et taxes.</p></div>}</>}
 {current&&<><h2>{current.title}</h2><p className="saas-muted">{current.description}</p><div className="saas-panel"><h3>{edit?'Modifier la fiche':'Nouvel enregistrement'}</h3><form key={edit?.id||tab} className="saas-form" onSubmit={saveRow}>{current.fields.map(f=><label key={f.key}>{f.label}{f.options?<select name={f.key} required defaultValue={edit?.[f.key]||f.options[0]}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:<input name={f.key} type={f.type||'text'} required={f.required} min={f.type==='number'?(['people','capacity'].includes(f.key)?1:0):undefined} step={f.type==='number'?'any':undefined} defaultValue={edit?.[f.key]||''}/>}</label>)}<div className="saas-form-actions"><button className="saas-primary">{edit?'Enregistrer les modifications':'Ajouter'}</button>{edit&&<button type="button" onClick={()=>setEdit(null)}>Annuler</button>}</div></form></div><input className="saas-search" aria-label="Rechercher" placeholder="Rechercher dans ce module…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="saas-table-wrap"><table><thead><tr>{current.fields.map(f=><th key={f.key}>{f.label}</th>)}{tab==='paiements'&&<th>Solde</th>}<th>Actions</th></tr></thead><tbody>{(ws.rows[tab]||[]).filter(r=>Object.values(r).some(v=>v.toLowerCase().includes(search.toLowerCase()))).map(r=><tr key={r.id}>{current.fields.map(f=><td key={f.key}>{r[f.key]}</td>)}{tab==='paiements'&&<td>{money(Number(r.total)-Number(r.paid))}</td>}<td><button onClick={()=>setEdit(r)}>Modifier</button><button onClick={()=>{if(confirm('Supprimer cet enregistrement de démonstration ?'))setWs({...ws,rows:{...ws.rows,[tab]:ws.rows[tab].filter(x=>x.id!==r.id)}})}}>Supprimer</button></td></tr>)}</tbody></table>{!ws.rows[tab]?.length&&<p className="saas-empty">Aucun enregistrement. Ajoutez votre première fiche ci-dessus.</p>}</div></>}
 {industry==='tourisme'&&['stock','recipes','sales'].includes(tab)&&<Restaurant tab={tab} ws={ws} setWs={setWs} setNotice={setNotice}/>}
 </main></div></>
}
export function Restaurant({tab,ws,setWs,setNotice}:{tab:string;ws:Data;setWs:(d:Data)=>void;setNotice:(s:string)=>void}){
 const [recipe,setRecipe]=useState(ws.recipes[0]?.id||'')
 const [parts,setParts]=useState<Recipe['items']>([])
 const [selected,setSelected]=useState(ws.ingredients[0]?.id||'')
 const [qty,setQty]=useState('0.1')
 function ingredient(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const id=crypto.randomUUID();setWs({...ws,ingredients:[...ws.ingredients,{id,name:String(d.get('name')),unit:String(d.get('unit')),stock:Number(d.get('stock')),cost:Number(d.get('cost')),threshold:Number(d.get('threshold'))}]});e.currentTarget.reset()}
 function addRecipe(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!parts.length){setNotice('Ajoutez au moins un ingrédient.');return}const d=new FormData(e.currentTarget);setWs({...ws,recipes:[...ws.recipes,{id:crypto.randomUUID(),name:String(d.get('name')),price:Number(d.get('price')),items:parts}]});setParts([]);e.currentTarget.reset()}
 return <><h2>{tab==='stock'?'Les bons ingrédients. Le bon stock.':tab==='recipes'?'Des recettes rentables, des prix maîtrisés.':'Commandes & ventes restaurant'}</h2>
 {tab==='stock'&&<><form className="saas-panel saas-form" onSubmit={ingredient}><label>Ingrédient<input name="name" required/></label><label>Unité<select name="unit"><option>kg</option><option>L</option><option>pièce</option></select></label><label>Stock initial<input name="stock" type="number" min="0" step="any" required/></label><label>Coût / unité (MAD)<input name="cost" type="number" min="0" step="any" required/></label><label>Seuil d’alerte<input name="threshold" type="number" min="0" step="any" required/></label><button className="saas-primary">Ajouter l’ingrédient</button></form><div className="saas-module-grid">{ws.ingredients.map(i=><article className="saas-panel" key={i.id}><h3>{i.name}</h3><strong>{i.stock.toFixed(2)} {i.unit}</strong><p>{money(i.cost)} / {i.unit}</p><p>{i.stock<=i.threshold?'Stock à réapprovisionner':'Stock disponible'} · seuil {i.threshold}</p><form onSubmit={e=>{e.preventDefault();const quantity=Number(new FormData(e.currentTarget).get('quantity'));setWs({...ws,ingredients:ws.ingredients.map(x=>x.id===i.id?{...x,stock:x.stock+quantity}:x)});e.currentTarget.reset()}}><label>Réception fournisseur<input name="quantity" type="number" min="0.01" step="any" required/></label><button>Réceptionner</button></form></article>)}</div></>}
 {tab==='recipes'&&<><form className="saas-panel saas-form" onSubmit={addRecipe}><label>Nom du plat<input name="name" required/></label><label>Prix de vente (MAD)<input name="price" type="number" min="0" step="any" required/></label><label>Ingrédient<select value={selected} onChange={e=>setSelected(e.target.value)}>{ws.ingredients.map(i=><option key={i.id} value={i.id}>{i.name} ({i.unit})</option>)}</select></label><label>Quantité par portion<input type="number" min="0.001" step="any" value={qty} onChange={e=>setQty(e.target.value)}/></label><button type="button" onClick={()=>{if(selected&&Number(qty)>0)setParts([...parts,{ingredient:selected,quantity:Number(qty)}])}}>Ajouter à la recette</button><div>{parts.map((part,i)=><p key={i}>{ws.ingredients.find(x=>x.id===part.ingredient)?.name} · {part.quantity} <button type="button" onClick={()=>setParts(parts.filter((_,n)=>n!==i))}>Retirer</button></p>)}</div><button className="saas-primary">Créer la recette</button></form><div className="saas-module-grid">{ws.recipes.map(r=>{const cost=recipeCost(r,ws.ingredients);return <article key={r.id} className="saas-panel"><h3>{r.name}</h3><label>Prix de vente (MAD)<input aria-label={'Prix de '+r.name} type="number" min="0" step="any" value={r.price} onChange={e=>setWs({...ws,recipes:ws.recipes.map(x=>x.id===r.id?{...x,price:Math.max(0,Number(e.target.value))}:x)})}/></label><p>Coût ingrédients : {money(cost)}</p><p>Marge ingrédients : {money(r.price-cost)} · {r.price?((r.price-cost)/r.price*100).toFixed(1):'0'} %</p><small>Hors main-d’œuvre, charges, pertes et taxes.</small></article>})}</div></>}
 {tab==='sales'&&<><p className="saas-muted">Chaque vente décrémente les ingrédients de sa recette. Le coût est figé au moment de la vente.</p><form className="saas-panel saas-form" onSubmit={e=>{e.preventDefault();try{setWs(sell(ws,recipe,Number(new FormData(e.currentTarget).get('quantity'))));setNotice('Vente enregistrée et stock actualisé.')}catch(error){setNotice((error as Error).message)}}}><label>Plat<select value={recipe} onChange={e=>setRecipe(e.target.value)}>{ws.recipes.map(r=><option key={r.id} value={r.id}>{r.name} · {money(r.price)}</option>)}</select></label><label>Portions<input name="quantity" type="number" min="1" step="1" defaultValue="1" required/></label><button className="saas-primary">Enregistrer la vente</button></form><div className="saas-table-wrap"><table><thead><tr><th>Date</th><th>Plat</th><th>Portions</th><th>Vente</th><th>Coût ingrédients</th><th>Marge ingrédients</th></tr></thead><tbody>{ws.sales.map(s=><tr key={s.id}><td>{new Date(s.date).toLocaleString('fr-FR')}</td><td>{s.recipe}</td><td>{s.quantity}</td><td>{money(s.total)}</td><td>{money(s.cost)}</td><td>{money(s.total-s.cost)}</td></tr>)}</tbody></table>{!ws.sales.length&&<p className="saas-empty">Aucune vente enregistrée.</p>}</div></>}
 </>
}
