import { useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate } from '@tanstack/react-router'
import { ArrowRight, Briefcase, CalendarDays, Check, CircleAlert, FileText, Gauge, Home, Inbox, LogOut, MapPin, Network, Receipt, ShieldCheck, Star, UserRound, UsersRound } from 'lucide-react'
import { useDemo } from '@/store/store'
import { useAuth } from '@/features/auth/AuthContext'
import { PageHeader } from '@/components/layouts'
import { Badge, Button, Card, Input, Select } from '@/components/ui'
import { providerReasons } from '@/lib/operational'
import { ActivityPulse } from '@/components/ActivityPulse'
import type { DeliverableStatus, MissionStatus, Quote } from '@/types'

const nav = [
  ['/expert', 'Accueil', Home], ['/expert/demandes', 'Demandes', Inbox], ['/expert/missions', 'Missions', Briefcase],
  ['/expert/clients', 'Clients', UsersRound], ['/expert/agenda', 'Agenda', CalendarDays], ['/expert/propositions', 'Propositions', Receipt],
  ['/expert/documents', 'Documents', FileText], ['/expert/performance', 'Performance', Gauge], ['/expert/profil', 'Profil', UserRound],
] as const

export function ExpertShell({ children }: { children: ReactNode }) {
  const auth = useAuth()
  const navigate = useNavigate()
  return <div className="expert-workspace"><aside><div className="expert-brand"><span>A</span><div><strong>ALLNEEDS</strong><small>Expert / Partenaire</small></div></div><nav>{nav.map(([to, label, Icon]) => <Link key={to} to={to as any} activeProps={{ 'data-status': 'active' }}><Icon size={16}/>{label}</Link>)}</nav><p className="expert-demo-note"><strong>DÉMO · DONNÉES FICTIVES</strong><br/>Les actions de cet espace sont enregistrées localement dans ce navigateur. Aucun devis ou message n’est envoyé à un vrai client.</p><button type="button" onClick={() => { void auth.logout().catch(() => undefined); void navigate({ to: '/' }) }} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-ink-200 bg-white px-3 py-2 text-xs font-semibold text-ink-700"><LogOut size={15}/>Quitter cet espace</button></aside><main>{children}</main></div>
}

type ExpertKind = 'home' | 'demandes' | 'missions' | 'clients' | 'agenda' | 'propositions' | 'documents' | 'performance' | 'profil'
type QuoteDraft = { amount: string; delayWeeks: string; validUntil: string; detail: string }
const dateInDays = (days: number) => { const d = new Date(); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10) }
const money = (n: number) => new Intl.NumberFormat('fr-MA', { maximumFractionDigits: 0 }).format(n)
const readableDate = (value: string) => new Date(value).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short', year: 'numeric' })
const quoteLabel: Record<Quote['status'], string> = { recu: 'Transmis', en_etude: 'En étude', accepte: 'Accepté', refuse: 'Refusé' }
const milestoneLabel: Record<DeliverableStatus, string> = { en_attente: 'À préparer', en_relecture: 'À valider', valide: 'Validé', retouche: 'À retoucher' }

export function ExpertSection({ kind }: { kind: ExpertKind }) {
  const { state, dispatch } = useDemo()
  const provider = state.providers[0]
  const [drafts, setDrafts] = useState<Record<string, QuoteDraft>>({})
  const [profileSaved, setProfileSaved] = useState(false)
  const [search, setSearch] = useState('')
  const [clientFilter, setClientFilter] = useState('Tous')
  if (!provider) return <PageHeader eyebrow="Expert / Partenaire" title="Aucun profil partenaire disponible." description="Ajoutez un prestataire dans les données de démonstration pour ouvrir cet espace."/>

  const needs = state.needs.filter((n) => n.candidateIds.includes(provider.id))
  const orgIds = new Set(needs.map((n) => n.orgId))
  const orgs = state.orgs.filter((o) => orgIds.has(o.id))
  const quotes = state.quotes.filter((q) => q.providerId === provider.id)
  const meetings = state.meetings.filter((m) => orgIds.has(m.orgId))
  const docs = state.documents.filter((d) => orgIds.has(d.orgId))
  const missions = state.missions.filter((m) => orgIds.has(m.orgId))
  const deliverables = state.deliverables.filter((d) => missions.some((m) => m.id === d.missionId))
  const needsToQuote = needs.filter((n) => !quotes.some((q) => q.needId === n.id))
  const unansweredMeetings = meetings.filter((m) => m.status === 'propose')

  if (kind === 'home') return <>
    <PageHeader eyebrow="Votre espace partenaire" title={`Bonjour ${provider.name}.`} description="Les demandes qui vous correspondent, les devis à transmettre et les missions à faire avancer — réunis au même endroit."/>
    <section className="expert-hero-action"><div><small>PROCHAINE ACTION</small><h2>{needsToQuote.length ? `Répondre à ${needsToQuote.length} demande${needsToQuote.length > 1 ? 's' : ''} qualifiée${needsToQuote.length > 1 ? 's' : ''}` : unansweredMeetings.length ? 'Confirmer votre prochain rendez-vous' : deliverables.some((d) => d.status === 'retouche') ? 'Reprendre un livrable à retoucher' : 'Votre espace est à jour'}</h2><p>{needsToQuote.length ? `Votre expertise correspond à « ${needsToQuote[0].title} ». Consultez le besoin, posez vos questions et transmettez un devis.` : 'Les prochaines étapes apparaîtront ici dès qu’un dossier demandera votre réponse.'}</p><Link to={needsToQuote.length ? '/expert/demandes' : unansweredMeetings.length ? '/expert/agenda' : '/expert/missions'}>{needsToQuote.length ? 'Voir les demandes' : unansweredMeetings.length ? 'Ouvrir l’agenda' : 'Voir mes missions'} <ArrowRight size={15}/></Link></div><div className="expert-hero-mark"><Network size={28}/><span>{needsToQuote.length ? needsToQuote.length : missions.length}</span><small>{needsToQuote.length ? 'à répondre' : 'mission(s)'}</small></div></section>
    <div className="expert-home-grid"><section><small>Demandes à chiffrer</small><strong>{needsToQuote.length}</strong><p>Besoin identifié, aucun devis de votre part.</p><Link to="/expert/demandes">Examiner <ArrowRight size={13}/></Link></section><section><small>Devis transmis</small><strong>{quotes.length}</strong><p>{quotes.filter((q) => q.status === 'accepte').length} accepté(s) · {quotes.filter((q) => q.status === 'en_etude' || q.status === 'recu').length} en attente.</p><Link to="/expert/propositions">Suivre les réponses <ArrowRight size={13}/></Link></section><section><small>Livrables à suivre</small><strong>{deliverables.filter((d) => d.status !== 'valide').length}</strong><p>Prochaine étape de vos missions actives.</p><Link to="/expert/missions">Ouvrir mes missions <ArrowRight size={13}/></Link></section><section><small>Rendez-vous à confirmer</small><strong>{unansweredMeetings.length}</strong><p>Créneaux proposés par les entreprises concernées.</p><Link to="/expert/agenda">Consulter l’agenda <ArrowRight size={13}/></Link></section></div>
    <section className="expert-home-lanes"><div><div className="expert-section-heading"><div><small>À FAIRE MAINTENANT</small><h2>Vos demandes prioritaires</h2></div><Link to="/expert/demandes">Toutes les demandes <ArrowRight size={14}/></Link></div>{needsToQuote.slice(0, 3).map((need) => <article key={need.id}><span className="expert-lane-icon"><Inbox size={17}/></span><div><small>{need.categoryLabel} · {need.location} {need.urgency === 'haute' ? '· urgent' : ''}</small><strong>{need.title}</strong><p>{need.budgetMax ? `Budget indicatif : jusqu’à ${money(need.budgetMax)} MAD` : 'Budget à confirmer avec le client'}{need.deadline ? ` · Échéance ${readableDate(need.deadline)}` : ''}</p></div><Link to="/expert/propositions">Préparer un devis <ArrowRight size={14}/></Link></article>)}{!needsToQuote.length ? <p className="expert-lane-empty">Pas de devis en attente de votre part. Consultez vos missions et les retours clients.</p> : null}</div><div className="expert-value-card"><small>CE QUE VOUS APPORTEZ</small><h2>Une réponse claire et fiable.</h2><ol><li><b>1</b><span>Vous vérifiez le périmètre et posez vos questions.</span></li><li><b>2</b><span>Vous proposez prix, délai et contenu du devis.</span></li><li><b>3</b><span>Le client choisit. Vous suivez ensuite le travail et ses livrables.</span></li></ol></div></section>
    <ActivityPulse activities={state.activities} orgIds={orgIds} title="Les entreprises progressent avec votre contribution" href="/expert/missions" />
  </>

  if (kind === 'demandes') return <>
    <PageHeader eyebrow="Demandes compatibles" title="Répondez aux besoins qui correspondent à votre expertise." description="Évaluez le périmètre, vérifiez votre disponibilité et transmettez une proposition claire. Le client décide ensuite."/>
    <div className="expert-list">{needs.map((n) => { const company = orgs.find((o) => o.id === n.orgId); const quote = quotes.find((q) => q.needId === n.id); return <article className="expert-request-card" key={n.id}><header><div><small>{n.categoryLabel} · {n.location} · {company?.name ?? 'Entreprise'}</small><h2>{n.title}</h2></div><Badge tone={n.urgency === 'haute' ? 'warning' : 'brand'}>{n.urgency === 'haute' ? 'Prioritaire' : 'À étudier'}</Badge></header><p>{n.description}</p><div className="expert-request-facts"><span><strong>Budget annoncé</strong>{n.budgetMax ? `Jusqu’à ${money(n.budgetMax)} MAD` : 'À préciser'}</span><span><strong>Échéance souhaitée</strong>{n.deadline ? readableDate(n.deadline) : 'À convenir'}</span><span><strong>Votre adéquation</strong>{providerReasons(provider, n).join(' · ') || 'Correspondance secteur / catégorie'}</span></div>{quote ? <div className="expert-inline-state"><Check size={16}/><span>Votre devis de {money(quote.amount)} MAD est transmis · {quoteLabel[quote.status]}</span><Link to="/expert/propositions">Suivre <ArrowRight size={13}/></Link></div> : <Link className="expert-primary-link" to="/expert/propositions">Préparer un devis pour ce besoin <ArrowRight size={15}/></Link>}</article> })}{!needs.length ? <Empty title="Aucune demande qualifiée pour le moment" detail="Une demande apparaîtra ici quand ALLNEEDS vous aura identifié comme partenaire potentiel."/> : null}</div>
  </>

  if (kind === 'propositions') return <>
    <PageHeader eyebrow="Propositions commerciales" title="Un devis complet, puis une décision claire." description="Précisez le prix, le délai et ce qui est inclus. Votre devis sera enregistré dans la démonstration et rattaché au besoin concerné."/>
    <div className="expert-proposal-queue">{needs.map((need) => { const current = quotes.filter((q) => q.needId === need.id); const draft = drafts[need.id] ?? { amount: '', delayWeeks: '2', validUntil: dateInDays(14), detail: '' }; const update = (key: keyof QuoteDraft, value: string) => setDrafts((all) => ({ ...all, [need.id]: { ...draft, [key]: value } })); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const amount = Number(draft.amount); if (!amount || amount <= 0 || !draft.detail.trim()) return; const quote: Quote = { id: `quote-${crypto.randomUUID()}`, needId: need.id, providerId: provider.id, amount, currency: 'MAD', delayWeeks: Number(draft.delayWeeks), validUntil: draft.validUntil, status: 'recu', receivedAt: new Date().toISOString(), detail: draft.detail.trim(), breakdown: [{ label: 'Prestation proposée', amount }] }; dispatch({ type: 'QUOTE_ADD', quote }); setDrafts((all) => ({ ...all, [need.id]: { ...draft, amount: '', detail: '' } })) }; return <Card key={need.id} className="expert-proposal-card"><header><div><small>{need.categoryLabel} · {need.location}</small><h2>{need.title}</h2><p>{need.budgetMax ? `Budget client jusqu’à ${money(need.budgetMax)} MAD` : 'Budget à confirmer'} · {need.urgency === 'haute' ? 'Prioritaire' : 'Demande qualifiée'}</p></div><Badge>{current.length ? `${current.length} devis transmis` : 'Réponse attendue'}</Badge></header>{current.map((q) => <div className="expert-quote-row" key={q.id}><Receipt size={16}/><div><strong>{money(q.amount)} MAD · {q.delayWeeks} semaine(s)</strong><small>Valable jusqu’au {readableDate(q.validUntil)} · {quoteLabel[q.status]}</small></div><p>{q.detail}</p></div>)}<form className="expert-quote-form" onSubmit={submit}><h3>{current.length ? 'Nouvelle version du devis' : 'Votre proposition'}</h3><label>Montant (MAD)<Input required min="1" type="number" value={draft.amount} onChange={(e) => update('amount', e.target.value)} placeholder="Ex. 12 500"/></label><label>Délai (semaines)<Input required min="1" type="number" value={draft.delayWeeks} onChange={(e) => update('delayWeeks', e.target.value)} /></label><label>Valable jusqu’au<Input required type="date" value={draft.validUntil} onChange={(e) => update('validUntil', e.target.value)}/></label><label className="expert-quote-detail">Contenu et conditions<Input required value={draft.detail} onChange={(e) => update('detail', e.target.value)} placeholder="Livrables, limites et conditions de paiement"/></label><Button type="submit"><Receipt size={15}/> Transmettre le devis</Button></form></Card> })}{!needs.length ? <Empty title="Aucun besoin auquel répondre" detail="Vos demandes qualifiées s’afficheront ici pour préparer une proposition."/> : null}</div>
  </>

  if (kind === 'missions') return <>
    <PageHeader eyebrow="Exécution et livrables" title="Faites avancer les missions acceptées." description="Mettez à jour vos livrables pour que le client et ALLNEEDS voient le même avancement."/>
    <div className="expert-list">{missions.map((mission) => { const company = orgs.find((o) => o.id === mission.orgId); const missionDeliverables = deliverables.filter((d) => d.missionId === mission.id); const done = missionDeliverables.filter((d) => d.status === 'valide').length; return <Card className="expert-mission-card" key={mission.id}><header><div><small>{mission.ref} · {company?.name ?? 'Entreprise'} · échéance {readableDate(mission.targetEnd)}</small><h2>{mission.title}</h2><p>{mission.owner} · {done}/{missionDeliverables.length} livrable(s) validé(s)</p></div><Select aria-label={`État de la mission ${mission.title}`} value={mission.status} onChange={(e) => dispatch({ type: 'MISSION_SET_STATUS', id: mission.id, status: e.target.value as MissionStatus })}><option value="cadrage">Cadrage</option><option value="en_cours">En cours</option><option value="livraison">Livraison</option><option value="accompagnement">Accompagnement</option><option value="terminee">Terminée</option></Select></header><div className="expert-deliverables">{missionDeliverables.map((item) => <article key={item.id}><span className={`expert-deliverable-dot ${item.status}`}/><div><strong>{item.title}</strong><small>{item.type} · v{item.version}/{item.maxVersions} · {milestoneLabel[item.status]}</small></div>{item.status === 'retouche' ? <Button size="sm" onClick={() => dispatch({ type: 'DELIVERABLE_SET_STATUS', id: item.id, status: 'en_relecture' })}>Renvoyer en relecture</Button> : item.status === 'en_attente' ? <Button size="sm" variant="outline" onClick={() => dispatch({ type: 'DELIVERABLE_SET_STATUS', id: item.id, status: 'en_relecture' })}>Soumettre au client</Button> : null}</article>)}</div></Card> })}{!missions.length ? <Empty title="Aucune mission attribuée" detail="Une mission apparaîtra ici lorsque le client aura accepté un devis et que le démarrage sera confirmé."/> : null}</div>
  </>

  if (kind === 'clients') return <><PageHeader eyebrow="Relations suivies" title="Les clients reliés à vos dossiers." description="Retrouvez le contexte de chaque entreprise et les sujets sur lesquels vous intervenez."/><div className="expert-client-toolbar"><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Rechercher une entreprise…"/><Select value={clientFilter} onChange={(e) => setClientFilter(e.target.value)}><option>Tous</option>{[...new Set(orgs.map((o) => o.sector))].map((sector) => <option key={sector}>{sector}</option>)}</Select></div><div className="expert-list">{orgs.filter((o) => (clientFilter === 'Tous' || o.sector === clientFilter) && `${o.name} ${o.city}`.toLowerCase().includes(search.toLowerCase())).map((o) => { const related = needs.filter((n) => n.orgId === o.id); return <article key={o.id}><small>{o.sector} · {o.city}</small><h2>{o.name}</h2><p>{o.kind} · {o.size}</p><div className="expert-client-tags">{related.map((n) => <span key={n.id}>{n.title}</span>)}</div></article> })}{!orgs.length ? <Empty title="Pas encore de client relié" detail="Une entreprise sera ajoutée lorsqu’un de vos devis ou besoins lui sera associé."/> : null}</div></>

  if (kind === 'agenda') return <><PageHeader eyebrow="Agenda partagé" title="Rendez-vous en contexte." description="Confirmez les créneaux proposés et retrouvez le dossier concerné avant chaque échange."/><div className="expert-list">{meetings.sort((a, b) => a.at.localeCompare(b.at)).map((m) => <article className="expert-meeting-card" key={m.id}><small>{new Date(m.at).toLocaleString('fr-FR', { dateStyle: 'full', timeStyle: 'short' })} · {m.durationMin} min</small><h2>{m.title}</h2><p><MapPin size={14}/> {m.location} · {orgs.find((o) => o.id === m.orgId)?.name} · {m.status}</p>{m.agenda.length ? <ul>{m.agenda.slice(0, 3).map((point) => <li key={point}>{point}</li>)}</ul> : null}{m.status === 'propose' ? <div className="expert-inline-actions"><Button size="sm" onClick={() => dispatch({ type: 'MEETING_SET_STATUS', id: m.id, status: 'confirme' })}><Check size={14}/> Confirmer</Button><Button size="sm" variant="outline" onClick={() => dispatch({ type: 'MEETING_SET_STATUS', id: m.id, status: 'annule' })}>Indisponible</Button></div> : m.status === 'confirme' ? <Button size="sm" variant="outline" onClick={() => dispatch({ type: 'MEETING_SET_STATUS', id: m.id, status: 'realise' })}>Marquer comme réalisé</Button> : null}</article>)}{!meetings.length ? <Empty title="Agenda libre" detail="Vos rendez-vous apparaîtront ici avec le client et le besoin associé."/> : null}</div></>

  if (kind === 'documents') return <><PageHeader eyebrow="Pièces de mission" title="Les documents utiles aux dossiers confiés." description="Chaque document reste rattaché à son entreprise. Les changements ci-dessous sont enregistrés dans la démonstration."/><div className="expert-list">{docs.map((d) => <article className="expert-document-row" key={d.id}><FileText size={19}/><div><small>{d.kind} · {orgs.find((o) => o.id === d.orgId)?.name} · {d.status}</small><h2>{d.name}</h2><p>{d.comment || 'Aucun commentaire.'}</p></div><Select aria-label={`État de ${d.name}`} value={d.status} onChange={(e) => dispatch({ type: 'DOC_SET_STATUS', id: d.id, status: e.target.value as 'demande' | 'recu' | 'valide' })}><option value="demande">Demandé</option><option value="recu">Reçu</option><option value="valide">Validé</option></Select></article>)}{!docs.length ? <Empty title="Aucun document partagé" detail="Les pièces nécessaires apparaîtront uniquement lorsqu’elles seront reliées à une demande ou une mission."/> : null}</div></>

  if (kind === 'performance') return <><PageHeader eyebrow="Votre activité partenaire" title="Des repères qui reflètent votre travail." description="Suivez vos réponses, les décisions prises et les livrables acceptés. Les chiffres proviennent des dossiers reliés à votre profil."/><div className="expert-home-grid"><section><small>Demandes reçues</small><strong>{needs.length}</strong><p>Correspondant à votre profil.</p></section><section><small>Devis acceptés</small><strong>{quotes.filter((q) => q.status === 'accepte').length}</strong><p>Sur {quotes.length} devis transmis.</p></section><section><small>Livrables validés</small><strong>{deliverables.filter((d) => d.status === 'valide').length}</strong><p>Sur {deliverables.length} livrable(s) suivi(s).</p></section><section><small>Avis clients</small><strong><Star size={17} fill="currentColor"/> {provider.rating.toFixed(1)}</strong><p>{provider.reviews} avis enregistrés · {provider.references.length} références.</p></section></div><section className="expert-performance-panel"><h2>Devis et décisions</h2>{quotes.map((quote) => <article key={quote.id}><span>{needs.find((n) => n.id === quote.needId)?.title ?? 'Demande'}</span><strong>{money(quote.amount)} MAD</strong><Badge tone={quote.status === 'accepte' ? 'success' : quote.status === 'refuse' ? 'neutral' : 'warning'}>{quoteLabel[quote.status]}</Badge></article>)}{!quotes.length ? <p>Aucun devis transmis : vos indicateurs apparaîtront dès votre première proposition.</p> : null}</section></>

  if (kind === 'profil') return <ProfileEditor key={provider.id} provider={provider} dispatch={dispatch} saved={profileSaved} onSaved={() => { setProfileSaved(true); window.setTimeout(() => setProfileSaved(false), 2500) }}/>

  return <Empty title="Aucune activité disponible" detail="Revenez à l’accueil partenaire pour consulter vos prochaines actions."/>
}

function ProfileEditor({ provider, dispatch, saved, onSaved }: { provider: NonNullable<ReturnType<typeof useDemo>['state']['providers'][number]>; dispatch: ReturnType<typeof useDemo>['dispatch']; saved: boolean; onSaved: () => void }) {
  const [form, setForm] = useState({ city: provider.city, priceHint: provider.priceHint, responseDelay: provider.responseDelay, note: provider.note, references: provider.references.join('\n') })
  const set = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value }))
  return <><PageHeader eyebrow="Profil partenaire" title={provider.name} description="Tenez vos informations à jour pour recevoir des demandes adaptées et aider les clients à décider."/><form className="expert-profile-form" onSubmit={(event) => { event.preventDefault(); dispatch({ type: 'PROVIDER_PATCH', id: provider.id, patch: { city: form.city, priceHint: form.priceHint, responseDelay: form.responseDelay, note: form.note, references: form.references.split('\n').map((x) => x.trim()).filter(Boolean) } }); onSaved() }}><section className="expert-profile-highlight"><ShieldCheck size={20}/><div><strong>{provider.categoryLabel} · {provider.verification === 'approfondie' ? 'Vérification approfondie' : 'Vérification de base'}</strong><p>Note {provider.rating.toFixed(1)}/5 · {provider.reviews} avis · Assurance {provider.insurance ? 'déclarée' : 'à renseigner'}</p></div></section><label>Ville<Input value={form.city} onChange={(e) => set('city', e.target.value)}/></label><label>Fourchette ou repère tarifaire<Input value={form.priceHint} onChange={(e) => set('priceHint', e.target.value)} placeholder="Ex. selon périmètre, à partir de…"/></label><label>Délai habituel de réponse<Input value={form.responseDelay} onChange={(e) => set('responseDelay', e.target.value)}/></label><label className="expert-profile-wide">Présentation et spécialités<Input value={form.note} onChange={(e) => set('note', e.target.value)} placeholder="Décrivez votre approche et vos spécialités"/></label><label className="expert-profile-wide">Références (une par ligne)<textarea value={form.references} onChange={(e) => set('references', e.target.value)} rows={4}/></label><div className="expert-profile-submit">{saved ? <span><Check size={15}/> Profil enregistré dans la démonstration</span> : null}<Button type="submit">Enregistrer mon profil</Button></div></form></>
}

function Empty({ title, detail }: { title: string; detail: string }) { return <div className="expert-empty"><CircleAlert size={21}/><div><strong>{title}</strong><p>{detail}</p></div></div> }
